### ISSUE TITLE
restore a backup? consistent snapshots?

### ISSUE THREAD

**Issue by tribalvibes** [backup/backup#115]
This looks like an elegant tool, but how do we restore the backups created?  At the very least there should be a complete restore-and-compare function to test that the backup is being generated correctly, and that it can in fact be restored in production.

A broader issue is how does this maintain consistency e.g. between databases and the file system?  Locking the database is problematic in practice and also does not solve the cross-database consistency. 

It seems like it would be appropriate to use volume-level snapshotting to create a consistent target for backup to run against. Any chance of baking this into the gem since it would be a common requirement?

**Comment by Ajedi32** [comment]
Related feature request: backup/backup-features#28
