### ISSUE TITLE
sftp/scp with public key authentication

### ISSUE THREAD

**Issue by aurels** [backup/backup#211]
Hi,

Maybe I missed something but isn't it possible to use SSH-backed storages without password, using public key authentication instead ?

Thanks.

**Comment by mtx-z** [comment]
Hello, I tried to use SFTP using key authentication but couldn't succeed. All ok if i re-enabled and use plaintext SSH password login. I would like to use only privatekey and passphrase.

I tested my keys/passphrase with manual SSH successfuly. 

I tried (from [here](http://backup.github.io/backup/v4/storage-rsync/)): 

```
store_with SFTP do |server|
  server.username = 'user'
  #server.password = 'there_is_no_pass_for_ssh_as_use_key'
  server.ip       = 'xx.xx.xx.xx'
  server.port     = 12345
  server.path     = '/path/to/store'
  server.keep     = 5

  # Additional options for the SSH connection.
  server.ssh_options = {
	:forward_agent => true,
	:host_key => "ssh-rsa",
	:encryption => "aes256-cbc", #verified, and seems supported from [the code](https://www.apt-browse.org/browse/debian/wheezy/main/all/ruby-net-ssh/1:2.5.2-2/file/usr/lib/ruby/vendor_ruby/net/ssh/transport/algorithms.rb)
	:compression => false, #also tried with zlib
	:passphrase => 'xxx',
	:keys => ['/path/to/private/key'], #929 from puttygen
	:keys_only => true
  }
end
```

I always get the error `could not settle on encryption_client algorithm` from netssh. I tried playing with the config without success. 

Thanks.
