### ISSUE TITLE
CLI Restore Command

### ISSUE THREAD

**Issue by yfeldblum** [backup/backup#243]
There should be a CLI command to restore a set of data sources based on the archive file, retrieved from storage and decrypted/decompressed.

The restore command should perfectly reverse the backup operation.

The restore command should take an option, which is a datetime-formatted string, specifying that the restore operation should restore from the most recent backup which is also from before that time.

If there are multiple storages, the restore command should take an option specifying which storage to pull from.

For example, the restore command should pull the most recent archive from remote storage, decrypt it, decompress it, and restore each database from the archive.

**Comment by Ajedi32** [comment]
Related feature request: backup/backup-features#28
