### ISSUE TITLE
Suggestion: Grandfather-Father-Sons rotation

### ISSUE THREAD

**Issue by ghost** [backup/backup#282]
I've used the [Grandfather-father-sons](http://en.wikipedia.org/wiki/Backup_rotation_scheme#Grandfather-father-son_backup) rotation scheme years now and find it a great way to get lots of extra coverage. It looks like you could implement it with the current configuration scheme, but I'd like to produce a pull request that makes doing this simpler.

What do you think? Would a patch with this feature be worth doing?

**Comment by sebastienbeau** [comment]
Hi @ghost, late is better than never, but I also think that the implementation of Grandfather-father-sons is something important to avoid the waste of resource! Simply sending a backup one per day and then removing the old one unwanted is clearly the best approach.
Do you still use backup gem? Are you still interested by this feature?
