### ISSUE TITLE
Remote backup of databases and files using ssh

### ISSUE THREAD

**Issue by dmitry** [backup/backup#298]
Is it possible somehow to make backups of the remote server using ssh?

For example I have several remote servers, that should be backuped locally. I need to backup not just files (I know that it's possible to make it using the rsync pull module), but also all the databases (mysql, postgres, redis, mongodb).

Thank you.

**Comment by 120dev** [comment]
If that can help you
https://github.com/backup/backup/issues/706#issuecomment-268532291
