### ISSUE TITLE
Suggestion: let's create CHANGELOG?

### ISSUE THREAD

**Issue by kuraga** [backup/backup#309]
Hello!

It seems to be `backup` hasn't changelog. Version numbering doesn't show appearence (or not) of major changes such as incompatibalities or new faetures.

Suggestion: let's create CHANGELOG?

**Comment by jhilden** [comment]
+1

**Comment by tombruijn** [comment]
We do have release notes: http://backup.github.io/backup/v4/release-notes/

**Comment by jhilden** [comment]
thanks a lot for the info @tombruijn 

maybe you also consider PR #704 a useful link
