### ISSUE TITLE
Backup complains about missing dependency even though it is installed

### ISSUE THREAD

**Issue by fullofcaffeine** [backup/backup#420]
Hi,

I'm using RVM to create an env just for the Backup gem. After upgrading the gem, I started getting the following error when trying to perform my backup:

```
> backup perform --trigger my_backup   
[2013/03/13 01:17:00][error] CLIError: Dependency::LoadError: Dependency Missing
[2013/03/13 01:17:00][error]   Gem Name: net-ssh
[2013/03/13 01:17:00][error]   Used for: SSH Protocol (SSH Storage)
[2013/03/13 01:17:00][error]   
[2013/03/13 01:17:00][error]   To install the gem, issue the following command:
[2013/03/13 01:17:00][error]   > backup dependencies --install net-ssh
[2013/03/13 01:17:00][error]   Please try again after installing the missing dependency.
```

I then installed net-ssh:

> gem install net-ssh  
> Successfully installed net-ssh-2.6.6
> 1 gem installed

I tried again, and got the same error.

If I try the suggested solution of running dependecies --install net-ssh, I get this:

```
 backup dependencies --install net-ssh
=== Bundler Detected ===
This command should not be run within a Bundler managed environment.
While it is possible to install Backup and it's dependencies using
Bundler, the gem version requirements must still be met as shown by:
> backup dependencies --list
```

But _I'm not_ using bundler. Here's the folder structure:

```
tree
.
├── config
│   ├── cron_log.log
│   └── schedule.rb
├── config.rb
├── data
│   └── my_backup
│       └── S3.yml
├── log
│   └── backup.log
└── other
    ├── Backup.sh
    ├── README
    └── home_exclude.txt
```

Any ideas?

Thanks,

Marcelo.

**Comment by marknguyen85** [comment]
> I've been using `3.0.27` without any problems. Installed `3.4.0` today on a new project and had `net-ssh` dependency error. Reverted back to `3.0.27` and everything was fine.
> 
> Note: I put `backup` in my `Gemfile` because it's convenient and easier to deploy.

worked.
