### ISSUE TITLE
Backup can't find the trigger when launched from a rake task

### ISSUE THREAD

**Issue by mottalrd** [backup/backup#530]
Hello,
I have this simple rake task invoking the backup gem

```
task :backup do
  backup_home = Rails.root.join('lib','backups')
  command =  "backup perform --root-path #{backup_home} --trigger my_backup"
  puts "Executing #{command}"
  sh command
end
```

my problem is that the task fails because the gem is not finding the trigger.

```
$ bundle exec rake backup
Executing backup perform --root-path <my_local_path_to_the_web_app>/lib/backups --trigger my_backup
[2014/03/08 12:57:24][error] CLIError: CLIError: No Models found for trigger(s) 'my_backup'.
rake aborted!
```

but suprisingly if I copy and paste in my shell the command, it works

```
backup perform --root-path <my_local_path_to_the_web_app>/lib/backups --trigger my_backup
```

I am using Backup gem v4, installed today.
Any help?

**Comment by Corstiaan84** [comment]
I am using backup from a rake task in exactly the same way as @mottalrd. I am still getting ````CLIError: CLIError: No Models found for trigger(s) 'backup'.```` unfortunately.

I am using dokku (docker) however. Does this matter perhaps? Should I install backup in the global gem set regardless? I prefer to keep it in the container...

Any ideas? Thanks!

**Comment by Corstiaan84** [comment]
Installing it in the global gem set (unsurprisingly) doesn't work either...

**Comment by tombruijn** [comment]
Hi @Corstiaan84, depending on the way you call the backup command in the rake task the environment of the rake task might not include backup. For example, your project with the rake task uses bundler and backup is not a member of that env. So instead shell out using `Bundler.with_clean_env` and then you backup should be available. I do not know enough about your scenario to really understand what the problem is, but I hope this helped

**Comment by Corstiaan84** [comment]
Hi @tombruijn thanks for getting back to me. I tried that already as well but to no avail. And doesn't the error ````CLIError: CLIError: No Models found for trigger(s) 'backup'```` imply that backup IS found but just not functioning correctly? I would expect a more generic error if the gem itself would not be found... Correct?

**Comment by tombruijn** [comment]
oops yeah, looks like I read to quickly.. 

This means backup cannot find your configuration. Is your model named `backup`? Is it in the `~/Backup/models/backup.rb` file and named correctly in the model file itself?

Can you post the command you run and the directory structure if that's not the problem?

**Comment by Corstiaan84** [comment]
I have reworked my solution by now but I used the exact same approach as @mottalrd
