### ISSUE TITLE
It seems not deleting the .tmp file

### ISSUE THREAD

**Issue by googya** [backup/backup#534]
the version I used is 3.2.0, and I backups the database about 20GB. when after backuping, there is a directory called .tmp whose size is 20GB still there. Will I delete the tmp directory manually?

**Comment by bastengao** [comment]
@googya  I also have the same issue. My disk is almost full, but the ~/Backup/.tmp size is 4G. Will it be deleted after backup perform?

**Comment by Nakilon** [comment]
Maybe offtopic, but why don't we use OS temp folders/files? http://programmers.stackexchange.com/q/314796/3385

**Comment by radeno** [comment]
Same issue.
Still left data in temporary folder.
I have combination of Local and SFTP strategy. Local is defined as last.
