### ISSUE TITLE
Where's the restore ;)

### ISSUE THREAD

**Issue by emilebosch** [backup/backup#601]
Hi guys, would it not be theoratically possible to build a restore function into backup? I mean you already know the db, names, the usernames/passwords. The location where the tars are stored? 

Would not be a lot of effort right? Theoretically that is ;) Does anyone know of any OS attempt at this?

**Comment by taf2** [comment]
:+1: how much to start today :money_with_wings:

**Comment by emilebosch** [comment]
one million million and five sheep please.

**Comment by fabn** [comment]
This gem seems so promising, however any backup system should really include a restore functionality. 

Without it it's boring and error prone to manually restore the generated backups (think to mysql and postgres).

Also a verification task to check generated archives would be great.

**Comment by tombruijn** [comment]
@fabn I'm not quite sure how the __backup__ gem becomes boring when it doesn't have a restore function?

If it's up to me I will never accept a PR adding a restore functionality. It should be a separate tool. I still want to make one, see if all the config can be reused to do the same actions in reverse, but not right now.

What would a verification task include? Almost all of the data comes from other tools. We can check a couple things, like if an archive is the type we expect and about the size of the expected archive, but not a lot else. Maybe a checksum of the uploaded version and the one generated during the backup?

**Comment by fabn** [comment]
> @fabn I'm not quite sure how the backup gem becomes boring when it doesn't have a restore function?

It's not the gem, it's the manual restore process that's boring.

> If it's up to me I will never accept a PR adding a restore functionality. It should be a separate tool. I still want to make one, see if all the config can be reused to do the same actions in reverse, but not right now.

I'd expect restore to be a companion tool something like a binary named `restore` that will read same configuration files as `backup` and do the opposite thing. Something like

```
$ restore -t my_backup --inplace # Restore all files in backup in their original position
$ restore -t my_backup --onto /foo # Restore all files using /foo as root
# If my_backup was a database this would restore it in another 
$ restore -t my_backup --onto new_db # Restore archived database to a new database named new_db
```

Or in an interactive manner

```
$ restore -t my_backup
# List all existing backups for `my_backup`
Which backup do you want to restore?
1) Backup #1 date ...
2) Backup #2 date ...
3) Backup #3 date ...
```
> What would a verification task include? Almost all of the data comes from other tools. We can check a couple things, like if an archive is the type we expect and about the size of the expected archive, but not a lot else. Maybe a checksum of the uploaded version and the one generated during the backup?

Indeed. Continuing the above example

```
$ verify -t my_backup # will check all archived backups against a pre computed signature or a checksum
```

I'm currently using [duply](http://duply.net/) which is a nice frontend to [duplicity](http://duplicity.nongnu.org/) but it doesn't provide all backup options as this gem, it only addresses filesystem backups. In order to backup a database you need to use pre scripts to dump it somewhere and then backup that portion of filesystem (you'll also need to configure cleanup). That said the proposed cli interface once properly configured is very good, restore is as simple as

```
$ duply <profile> status # list available backups
$ duply <profile> restore <target_path> [<age>] # restore the complete backup to <target_path> [as it was at <age>]
```

**Comment by tombruijn** [comment]
I formalized the request by adding an issue to backup-features: https://github.com/backup/backup-features/issues/28

Any other discussion can happen there or in [Gitter](https://gitter.im/backup/backup?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
