### ISSUE TITLE
S3: use_iam_profile

### ISSUE THREAD

**Issue by Ajaxy** [backup/backup#604]
Hello all.

How to setup iam profile to make backups with? I created IAM user in my AWS console and granted him needed permissions. As I see I should not setup `aws_access_key_id` and `aws_secret_access_key` fields when using IAM profile, but how to authenticate him then?

**Comment by panoschal** [comment]
I don't know what purpose does `s3.use_iam_profile = true` serve. I think Amazon does not refer to anything about IAM profiles, instead, it recommends using IAM users instead of the credentials of the root account.
