### ISSUE TITLE
how use "mysqldump --login-path=local" in Backup Gem ?

### ISSUE THREAD

**Issue by fadeev2010** [backup/backup#618]
if use:
mysqldump -u User -pPasswod DB > mysql.dump
Warning: Using a password on the command line interface can be insecure.

I want to use for safety:
setting once: 
  mysql_config_editor set --login-path=local --host=localhost --user=username --password

mysqldump --login-path=local DB_name  > mysql.dump

http://dev.mysql.com/doc/refman/5.6/en/mysql-config-editor.html

**Comment by tombruijn** [comment]
Sorry for the extreme long delay. The fix has been merged. Will be shipped with version 4.1.12.

**Comment by 45sound** [comment]
When is version 4.1.12 been released?

**Comment by tombruijn** [comment]
Only [just now](https://rubygems.org/gems/backup/versions/4.1.12). Thought I could wait and add some other fixes, but then forgot about it.  Thanks for poke @45sound
