### ISSUE TITLE
Trigger backup for all models doesn't work if --config-file specified

### ISSUE THREAD

**Issue by ivanstojkovicapps** [backup/backup#631]
I have the following:

backup perform --trigger db_backup --config-file config.rb 

this doesn't trigger backup of other models.

If i remove the --config-file and use the default, it triggers backup for all models

**Comment by tombruijn** [comment]
None of the logic should be different when you specify a config file. I tested it just now, it will run for every modal with that trigger name.

Is your config file in the default location? So if you wouldn't specify it, would it load the same file?
What did you configure in your config file?
