### ISSUE TITLE
Hide DB password when dump fails

### ISSUE THREAD

**Issue by akahn** [backup/backup#643]
When a backup fails during the dump stage (using postgres in my case), the database password is written to the log file (which then may be emailed). I request an option to strip the password from the log output.

**Comment by tombruijn** [comment]
Sorry, @akahn, totally missed this issue. You can request new features here: https://github.com/backup/backup-features/issues

Have you tried using a password file? I'm not sure how well pg supports this, but there some documentation on it here: http://www.postgresql.org/docs/9.1/static/libpq-pgpass.html
