### ISSUE TITLE
Unable to set component defaults in config.rb

### ISSUE THREAD

**Issue by varunpatro** [backup/backup#648]
in my config.rb, i have
`Database::MySQL.defaults do |db|`
`  db.name = "blog"`
`  db.name = "root"`
`end`

but when i create a new backup model using `backup generate:model --trigger testblog_backup --databases=mysql --storages=local`

i dont have the defaults i specified in config.rb

Whats the issue?

**Comment by tombruijn** [comment]
Please read: http://meskyanichi.github.io/backup/v4/component-defaults/

These values are not prefilled when you generate a new model (the behavior I think you're expecting).

They are loaded when you perform the backup so you don't have to set them in all your models.
