### ISSUE TITLE
backup 4.1.8 gem dependency conflict with fog-core 1.30

### ISSUE THREAD

**Issue by stevenolen** [backup/backup#649]
PR #644 appears to have created an impossible gem dependency issue given some of the changes in the fog-core gem:

backup 4.1.8 lists `excon =0.44.4` and `fog =1.28`
fog 1.28 lists `fog-core >=1.27.3, ~>1.27`
fog-core 1.30 (which is the latest version acceptable via the fog dep)  lists `excon ~>0.45`

Thanks!

**Comment by stevenolen** [comment]
I worked around in my situation by installing these versions in this order (I'm not using AWS anywhere so the fix in #644 isn't so important to me for now):

* fog-core 1.29
* fog 1.27
* backup 1.4.7

**Comment by tombruijn** [comment]
How exactly does it create an impossible gem dependency issue?

- What's the error?
- What ruby version are you running on?
- Are you executing the backup gem through bundle exec? If no, try installing and executing the gem through bundler.

**Comment by stevenolen** [comment]
Here's the error:
```
ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
    The user requires backup (= 4.1.8) but it conflicted:
  Activated excon-0.44.4 instead of (~> 0.45) via:
    fog-core-1.30.0, fog-1.28.0, backup-4.1.8
  Activated excon-0.44.4 instead of (~> 0.45) via:
    fog-core-1.30.0, fog-1.28.0, backup-4.1.8
```

I'm not executing through bundle exec but as a part of the the gofullstack/backup cookbook in chef.

Sorry if I wasn't clear in my last message: backup `4.1.8` requires **exactly** excon `0.44.4`, and also **exactly** fog `1.28`. fog `1.28`'s latest acceptable dependency on fog-core is fog-core `1.30` which requires `~>0.45`...so unless I'm mistaken or misunderstanding, on a system with none of these gems already installed fog-core 1.30 will require a version of excon too new for the backup gem? Obviously there is a way around it by installing fog-core 1.29, fog 1.27 and backup 4.1.7 manually, but gem doesn't seem to want to resolve that dependency on it's own.  I didn't attempt to manually resolve with 4.1.8 since I don't really need it for my purposes..

**Comment by stevenolen** [comment]
I also get it for 4.1.7:

```
ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
    The user requires backup (= 4.1.7) but it conflicted:
  Activated excon-0.44.1 instead of (~> 0.45) via:
    fog-core-1.30.0, fog-1.27.0, backup-4.1.7
  Activated excon-0.44.1 instead of (~> 0.45) via:
    fog-core-1.30.0, fog-1.27.0, backup-4.1.7
```

**Comment by tombruijn** [comment]
If you're installing/using this through the gofullstack/backup cookbook I don't see the problem?

I recommend installing it with bundler, because backup has too many dependencies and hard locks on gems nowadays to trust a simple gem install to figure out.

So if the cookbook doesn't use it, maybe they should change that? Because the setup now will only work if your installing the backup gem for the first time and no gems from other projects are shared in that ruby installation.
