### ISSUE TITLE
Unable to perform backup with non-default config path 

### ISSUE THREAD

**Issue by lkairies** [backup/backup#653]
Hi,

When I try to perform a backup with a non-default config file I get a CLIError:
```
backup perform -t redis_postgres --config-file config/backup/config.rb
CLIError: ArgumentError: wrong number of arguments (1 for 0)
```

My config file just sets the root, tmp and data_path like this:
```
...
root_path '/home/lkairies/mercuriel/ciwor/config/backup'

tmp_path  '/home/lkairies/backups/.tmp'

data_path '/home/lkairies/backups/.data'
...
```

When I comment out all configurations in the config file and retry the command I get another CLIError
```
backup perform -t redis_postgres --config-file config/backup/config.rb
CLIError: CLIError: No Models found for trigger(s) 'redis_postgres'.
```

Any idea why this is happening?

**Comment by tombruijn** [comment]
It looks like that whatever your trying to backup is throwing an error, not necessarily the configuration itself.

You could try using a full path `/path/to/my/config.rb` instead as well, to see if that works.

But I can't really tell you more without your full config.rb and #{model_name}.rb files

**Comment by lkairies** [comment]
I solved it for now.

I commented out the root_path in my config file and it worked. It also works with the configured root_path and the default config path.

**Comment by tombruijn** [comment]
So it's fixed then, not a bug?
