### ISSUE TITLE
Bug when passing frozen string to s3.path

### ISSUE THREAD

**Issue by dmishh** [backup/backup#655]
When setting up configuration param `s3.path` using frozen string (such as `ENV` values) an error `RuntimeError: can't modify frozen String` occurs:

```
store_with S3 do |s3|
  s3.path = ENV['AWS_BACKUP_PATH']
end
```

The problem is in this line: https://github.com/backup/backup/blob/40399aa06dc9fbdaea60c627936a66e2adaf35e4/lib/backup/storage/s3.rb#L79

Fix:  #654

Temporary workaround:

```
store_with S3 do |s3|
  s3.path = ENV['AWS_BACKUP_PATH'].dup
end
```

**Comment by tombruijn** [comment]
@dmishh thanks for the report and PR. I merged it. I don't know when I'll release a new version. I'm waiting on some fixing/closing some other issues first

**Comment by tombruijn** [comment]
Backup 4.1.9 containing this fix has been released!

**Comment by dmishh** [comment]
:+1:
