### ISSUE TITLE
Is it not possible to use storage on an individual db in an array?

### ISSUE THREAD

**Issue by mikeyhill** [backup/backup#656]
db_list.each do |db_name|
          database MySQL, db_name do |db|
          db.name               = db_name
          db.additional_options = ["--quick", "--single-transaction"]
       end
   
       store_with S3, db_name do |s3|
         s3.path                = "backups/#{env}/mysql/#{storage_id}"
         s3.keep                = keep
       end
     end

I was expecting that db1, db2, db3 would all be uploaded to s3 individually but instead I end up with one big tar with all the databases in them.  I would very much like to use my method if possible but haven't been able to accomplish this yet.

**Comment by tombruijn** [comment]
Hi @mikeyhill 

This question was asked before under issue #628. Please read there my advice on splitting up your backup model in multiple models.

There was also an issue created in the [feature issue tracker](https://github.com/backup/backup-features/issues/25) which is already accepted for the next major version of backup.

So it probably won't appear any time soon in v4, but v5 will use this backup strategy.

**Comment by mikeyhill** [comment]
Thanks @tombruijn for the clarification.  I scoured the issues but guess I was asking the wrong question.  I didn't see a branch for v5 development so I assume that hasn't begun yet.  I'll keep an eye out and see if I can contribute back some code (I may end up adding this in v4 if my time allows).

**Comment by tombruijn** [comment]
@mikeyhill we've started working on it, but it's not public yet. It's a bit of departure from v4 so we want to get it right before sharing it.

**Comment by mikeyhill** [comment]
Great - can't wait to check it out.  Cheers.
