### ISSUE TITLE
Changing the content of the email it sends?

### ISSUE THREAD

**Issue by swaathi** [backup/backup#660]
I'd like to add some more information into the email that it sends out on success/failure of the backup. How do I go about this?

**Comment by tombruijn** [comment]
Hi @swaathi currently this is not possible. It uses a [template](https://github.com/backup/backup/tree/master/templates/notifier/mail) to set up the email contents. Unless you modify that template you can't change the contents.

What is it that you want to add to the email?

**Comment by swaathi** [comment]
Hi @tombruijn. I'd like to add a download link to the backed up file. Also it would be great if I could style the mail!

**Comment by tombruijn** [comment]
@swaathi currently it's not possible to add your own templates and thus do the things you want. You could hack a way around it by overriding the Backup::TEMPLATE_PATH constant on the Backup class. However, what might break everything else if you do..

So maybe it's an idea to make custom templates possible. I added an issue to the feature issue tracker https://github.com/backup/backup-features/issues/26

We'll look into it for the next major version. Maybe not it's first release but a release after that.
It's unlikely it will be added to v4 unless someone submits a PR for it.
