### ISSUE TITLE
mention date of v4 release in upgrade warning

### ISSUE THREAD

**Issue by matkoniecz** [backup/backup#661]
On upgrading gems following message is displayed:
```
    Thank you for installing Backup!

    See the Release Notes for changes in this version:
    http://backup.github.io/backup/v4/release-notes

    If you're upgrading from v3.x, be sure to read:
    http://backup.github.io/backup/v4/upgrading
```

It would be great to add date of v4 release ("v4 was released on 26 Jan 2014" or something similar) so people that are upgrading from later version are not scared (for example - I am not remembering my previous version, so during every update I am nervous that my backup script are broken and I look through commit log to discover that https://github.com/backup/backup/commit/cb34458c29e2dca07b80f2653c5eff0e10da7a2d was committed before I started using this tool).

**Comment by tombruijn** [comment]
To be honest I hate these messages and I want to remove them. Agreed @meskyanichi ?


People should look at what version of the gem they are using. Backup has-been/is-now using semver-ish versioning. Major versions are major changes: so watch out!

**Comment by meskyanichi** [comment]
Sure
