### ISSUE TITLE
Feature request: Disable tarring before uploading to Storage

### ISSUE THREAD

**Issue by dhampik** [backup/backup#662]
I'd like to refer issue #255 and request that feature again with little more explanation why it is good.

I suppose that when we have separate files for db backups and different folder is way much better rather than having a single tar file or even tar splitted in chunks. That is because in case if nework connection will fail or external storage will get out of space or something else, it is more likely to be able to have at least part of data backed up with possibility ot be easily restored.
In case of tar splitted in chunks it'll probably be harder to restore it in case when one of the chunks got lost or not all chunks were properly uploaded to external storage (is it possible at all to restore it in that case???).

Taking into account the fact that backups could usually be pretty big in size, it makes it even more significant not to upload all the data in a single file, but have it splitted into a separate self-containing archives (not chunks) which could be restored separetly.

**Comment by tombruijn** [comment]
Already suggested on the Feature issue tracker here https://github.com/backup/backup-features/issues/25

It's accepted and implemented in the next major version.

**Comment by tombruijn** [comment]
Tiny addition: We're not disabling tarring/compressing for most things. Unless no compressor is configured for the entire backup. So it's either compress everything or nothing.

Sources (databases, files, etc) will be in separate archives when being backed up, so no more big archives.

**Comment by dhampik** [comment]
Awesome! Thanks for info. You are doing a great thing!

**Comment by amerk86** [comment]
+1 for skipping tar + gzip. 

We have large DB tables that we wish they'd stay per file for easier recovery. Any work around at the moment?

**Comment by tombruijn** [comment]
@amerk86 you can create a model per configuration and run them separately

**Comment by amerk86** [comment]
@tombruijn Any example code or discussion thread to get me started?

**Comment by tombruijn** [comment]
@amerk86 not really. Just create a new model for every database/table, share parts of the config in the config.rb perhaps?

**Comment by amerk86** [comment]
Brain-fart! That's what I did. I misunderstood your previous comment. Thanks :)
