### ISSUE TITLE
Keep backups forever & change the name of backup files

### ISSUE THREAD

**Issue by xxxazxxx** [backup/backup#663]
I'll appreciate if you could help me to figure out the following : 

I never want the backup files to be deleted from S3, local, SCP, SSH.

Names of the backup are 2015.04.18.19.56.54 , 2015.04.18.20.06.56 , ... . I want to add a prefix name on an IF ELSE condition in the backup model file.

**Comment by tombruijn** [comment]
Why would you want to keep backups forever? You could just specify a very big number to keep like at least a million backups or something.

Take a look at issue #641 for how to change the filename.
