### ISSUE TITLE
Store directory without using an archive

### ISSUE THREAD

**Issue by jasperjorna** [backup/backup#664]
How can I store a directory with rsync or S3 without having to archive it first?

I know that within `sync_with` I can use `rsync.directories do |directory|` but how about `store_with`?

**Comment by Twiebie** [comment]
Ah, I guess syncing with different target paths could be an option.

**Comment by tombruijn** [comment]
@Twiebie would that work?

Otherwise  issue #662 pretty much answers your question

**Comment by Twiebie** [comment]
@tombruijn no luck so far.

I can't get rsync working with `sync_with` at all. It starts but hangs forever afterwards, although it does move some files.

I'm trying to figure out how to get some debug info, I specified -vv in the arguments but it's not giving me anything. Also the logs don't go further than:

```
[2015/05/12 14:29:07][info] Performing Backup for 'web02 data sync. (web02_data)'!
[2015/05/12 14:29:07][info] [ backup 4.1.10 : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux] ]
[2015/05/12 14:29:07][info] Syncer::RSync::Push Started...
[2015/05/12 14:29:07][info] Running system utility 'rsync'...
```

**Comment by tombruijn** [comment]
I can remember a similar issue where the backup would hang, but that involved a mysql database. I found some references pointing to the Open4 library as a potentially being the problem. When it receives too much output on STDOUT it wouldn't exit the process anymore, but I think it would actually complete the command, just not exist in ruby.

So does the command actually finish at some point or does rsync itself hangs somewhere halfway through?

Have you tried running rsync without the backup gem?
Does the command rsync command itself exit normally?
How many directories and files are you syncing?
How much output does it print in STDOUT?

**Comment by Twiebie** [comment]
Just ran the rsync command manually and it finished without problems.
It's around 67539 files and 15364 directories in this case.

The output is as shown above, or are you referring to something else?

**Comment by tombruijn** [comment]
Alright, so sync_with Rsync::Push doesn't work? Can you post your config? It never did complete the full sync right? So it stopped somewhere halfway, was the rsync process still running? `ps aux | grep rsync`

It's a lot of files so I can imagine a timeout is involved perhaps. How long does it take to sync this manually?

With STDOUT I mean the output you get when you perform the command manually. Usually rsync keeps quiet unless you specify it needs to verbose. It will only print output to STDOUT when warnings occur, like: `skipping non-regular file "Photos Library.photoslibrary/Database/Properties.apdb"` or whe it doesn't have enough permissions.

A workaround suggested for another issue was this: https://github.com/backup/backup/issues/617#issuecomment-67962629

So it just worked around backup pretty much by running rsync directly. Yes I know it's terrible and pretty sure backup v5 won't have this problem as it's not using open4 or something like that.

Let me know your config and I'll have another look.
