### ISSUE TITLE
Postgres server not connecting error

### ISSUE THREAD

**Issue by JPMallow** [backup/backup#665]
Hi,

I am using Postgres DB in our rails application and I was trying to use backup gem in this.

I have local postgres server running in my mac in the 5432 port. I was able to connect to my database using pgAdmin. But the backup gem says error like below.

Error:
ModelError: Backup for Description for db_backup (db_backup) Failed!
[2015/05/12 11:30:35][error]   An Error occured which has caused this Backup to abort before completion.
[2015/05/12 11:30:35][error]   Reason: Database::PipelineError
[2015/05/12 11:30:35][error]   Database::PostgreSQL Dump Failed!
[2015/05/12 11:30:35][error]   Pipeline STDERR Messages:
[2015/05/12 11:30:35][error]   (Note: may be interleaved if multiple commands returned error messages)
[2015/05/12 11:30:35][error]   
[2015/05/12 11:30:35][error]   pg_dump: [archiver (db)] connection to database "my_database_name" failed: could not connect to server: No such file or directory
[2015/05/12 11:30:35][error]    Is the server running locally and accepting
[2015/05/12 11:30:35][error]    connections on Unix domain socket "/tmp/pg.sock/.s.PGSQL.5432"?
[2015/05/12 11:30:35][error]   The following system errors were returned:
[2015/05/12 11:30:35][error]   Error: Errno::EPERM: Operation not permitted - 'PGPASSWORD='my_password'' returned exit code: 1

My DB Code:

  database PostgreSQL do |db|
    db.name              = "my_db_name"
    db.username        = "my_db_user_name"
    db.password        = "my_db_password"
    db.host                = "localhost"
    db.port                = 5432
  end 

I am using Postgres mac app to run my postgres server. Is this an cause of issue? Please help me to fix this issue.

Thanks.

**Comment by tombruijn** [comment]
How are you connecting to postgres with the mac app?

Are all the connection details the exact same?

- Is postgres running? Does `ps aux | grep postgres` return anything?
- Does it accept connections over the socket? Or is it configured to use tcp?

Find the `postgresql.conf` file on your system and look if the socket directory might have been changed. If you use homebrew, use `brew info postgres` to find the installation directory. It would be `/usr/local/var/postgres`

- Can you connect to postgres from the console?
  `PGPASSWORD=mypassword psql --host=localhost --port=5432 --username=my_user --dbname=my_db`

**Comment by tombruijn** [comment]
@JPMallow any luck with setting up the connection? Do you need any help? We're on [Gitter](https://gitter.im/backup/backup) if you need help debugging this

Without a response I'll close issue in a couple of day

**Comment by JPMallow** [comment]
I am using postgres mac app(http://postgresapp.com) to run postgres server locally. Usually I do "psql -d development_db" to connect my database. When I give "ps aux | grep postgres" I am able to see like below.

/Applications/Postgres.app/Contents/Versions/9.3/bin/postgres -D /Users/jayaprakash/Library/Application Support/Postgres/var-9.3

Yes. I am able connect postgres from the console using the command "PGPASSWORD=mypassword psql --host=localhost --port=5432 --username=my_user --dbname=my_db"

**Comment by tombruijn** [comment]
You can connect to it normally, but when backup calls it it throws a socket error? `connections on Unix domain socket "/tmp/pg.sock/.s.PGSQL.5432"` ? You're not setting any socket configuration? Either in backup on in the postgres config files?

You can try this command (replace the values with your own) and see if that works. That should be the same command as is run by backup with your configuration. If that does work from the terminal (without backup) I don't know what can be the problem.

```sh
PGPASSWORD=mypassword /usr/local/bin/pg_dump --username=my_db_user_name --host='localhost' --port='5432'    my_db_name
```

**Comment by JPMallow** [comment]
Let me check and come back to you if any issues

**Comment by lfzawacki** [comment]
I had the same problem, it was the  'db.socket' option which I left as the default value. In my server it wasn't located in '/tmp/pg.sock' , so try finding the correct location and editing the backup model.

**Comment by tombruijn** [comment]
Thanks for the info @lfzawacki! I hope it's the same problem @JPMallow is having. Any tips on finding the socket file? I see it's not always in the pg_hba.conf file

**Comment by lfzawacki** [comment]
I'm using arch and had to search for it on the postgresql page on the wiki. However it seems that in `postgresql.conf` there's  a `unix_sockets_directories` configuration, so maybe try there.

**Comment by cavneb** [comment]
I'm having the same problems. Running ubuntu 14.10

**Comment by cavneb** [comment]
This worked for me once I removed the socket line in the PG config

**Comment by tombruijn** [comment]
@JPMallow can you let us know if updating the socket config fixes the problem?

**Comment by JPMallow** [comment]
@tombruijn I do not have time to re check this issue. Please close the issue (if required), I will re open it if I face the issue again.

Thanks.
