### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by taf2** [backup/backup#672]
backup is great but without restore... Any plans to add features that support automatic restore of e.g. 

mysql (mysqldump, innobackupex)
postrgres
files

Maybe the job for another gem... e.g. restore :+1:

**Comment by tombruijn** [comment]
Hi @taf2, it's certainly something I'm interested in. I'd like to point you to issue #601 for my take on it. It's not something we would work on very soon, we'd like to finish the new version of backup first before starting work on something like this.

**Comment by Ajedi32** [comment]
Related feature request: backup/backup-features#28
