### ISSUE TITLE
Native Packages

### ISSUE THREAD

**Issue by luxflux** [backup/backup#673]
What do you think about providing DEB and RPM packages via [packagecloud.io](https://packagecloud.io)?

I'd rather like to install another package via `apt-get` than having to use `gem` and all the build dependencies like `ruby-dev`, 'make`, 'libxml-dev' and their dependencies to install some software.

By using [fpm](https://github.com/jordansissel/fpm) this should not be that hard. @bdossantos has already some [stuff in place](https://github.com/backup/backup/issues/595#issuecomment-59807422) to ease building these packages.

**Comment by tombruijn** [comment]
Hi @luxflux, currently we're not looking into this. Not sure how that would work with the ruby dependency.  Focussing on version 5 I see a lot less issues for distribution of this tool.
