### ISSUE TITLE
Storage::Cycler::Error: There was a problem removing the following package (wrong date in folder)

### ISSUE THREAD

**Issue by jmuheim** [backup/backup#674]
Warning:

```
[2015/06/16 21:30:07][info] Removing backup package dated 2015.06.08.11.25.57...
[2015/06/16 21:30:07][warn] Storage::Cycler::Error: There was a problem removing the following package:
[2015/06/16 21:30:07][warn]   Trigger: a4aa2 :: Dated: 2015.06.08.11.25.57
[2015/06/16 21:30:07][warn]   Package included the following 1 file(s):
[2015/06/16 21:30:07][warn]   a4aa2.tar
[2015/06/16 21:30:07][warn] --- Wrapped Exception ---
[2015/06/16 21:30:07][warn] Net::FTPPermError: 550 a4aa2/2015.06.08.11.25.57/a4aa2.tar: No such file or directory
```

It seems to try to remove a non-existing old backup.

My model:

```
  database MySQL do |db|
    # ...
  end

  archive :uploads do |archive|
    # ...
  end

  store_with FTP do |server|
    server.username     = 'XXX'
    server.password     = 'XXX'
    server.ip           = 'XXX'
    server.port         = 21
    server.path         = '~/'
    server.keep         = 10
    server.passive_mode = true
  end

  store_with Local do |local|
    local.path = '~/Backup/backups/'
    local.keep = 5
  end

  notify_by Mail do |mail|
    # ...
  end
```

When looking at the FTP folder, it has the following item: `2015.06.08.21.30.06`, which has the correct date (`2015.06.08`), but not the correct time (`21.30.06` instead of `11.25.57`)! What could be the problem? Some time zone issue?

I sometimes trigger a backup manually, could this interfere with the default automatic backup?

**Comment by tombruijn** [comment]
Hi @jmuheim, sorry for the delay. I got into an accident and was forced to take some time off.

About your problem. Triggering the backup manually shouldn't be a problem as long as you use the same command and config.

The time difference is a bit strange. Backup registers everything in UTC, so your own timezone should be ignored. In what time zone are you? Does it match up to the difference between timestamps?

You can have a look in the `~/Backup/.data` directory for your backup model. There you can see what archives are registered for the FTP storage. Let me know if it looks like there's a problem there. You can also post it.

**Comment by jmuheim** [comment]
The problem didn't occur again after some occurrences. Maybe it's because I deleted some old backups manually?

**Comment by tombruijn** [comment]
Could very well be the case. Backup doesn't like it when you mess with the data and/or archives that it wants to delete

**Comment by JimmySticks2001** [comment]
@tombruijn, I have the same problem. Is there any way to correct this error so I don't have the warning in my logs and emails?

**Comment by tombruijn** [comment]
@JimmySticks2001 You can fix this by opening `~/Backup/.data/{trigger_name}/{storage_name}.yml` and removing the entry in the yaml array that is mentioned in the error you are getting.

**Comment by JimmySticks2001** [comment]
@tombruijn. Neat! That did it, thanks :D
