### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by txssseal** [backup/backup#681]
I have my model configured to backup multiple servers in one go round.  Only problem is if one fails, the entire model fails.  Ive tried using begin rescue blocks, still no luck.  Is there another way of doing this within the model?

**Comment by tombruijn** [comment]
@txssseal would PR #676 fix your problem?

**Comment by tombruijn** [comment]
@txssseal version 4.1.11 has been released to fix this issue.

**Comment by txssseal** [comment]
@tombruijn works like a charm, thank you!
