### ISSUE TITLE
Can't unpack gzipped archive

### ISSUE THREAD

**Issue by noff** [backup/backup#684]
Using 
```
compress_with Gzip
``` 
in model config.

Archive uploads to storage with filename "database.tar".

When trying to untar it got error:
```
$ tar -zxf dbdump.tar 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Trying to untar without -z:
```
$ tar -vxf dbdump.tar 
dbdump/
dbdump/databases/
dbdump/databases/PostgreSQL.sql.gz
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

But in folder dbdump archive created:
```
$ ls -la dbdump/databases/PostgreSQL.sql.gz 
-rw-r--r-- 1 rails rails 5799851450 Jul 21 04:39 dbdump/databases/PostgreSQL.sql.gz
```

Trying to unpack it:
```
$ cd dbdump/databases/
rails@api:~/dbdump/databases$ gunzip PostgreSQL.sql.gz 
gzip: PostgreSQL.sql.gz: invalid compressed data--format violated
```

How to unpack backup packed with gem backup?

Using OS Debian 7. Versions of software:

```
$ tar --version
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by John Gilmore and Jay Fenlason.


$ gzip --version
gzip 1.5
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Written by Jean-loup Gailly.

$ gunzip --version
gunzip (gzip) 1.5
Copyright (C) 2007, 2011-2012 Free Software Foundation, Inc.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Written by Paul Eggert.


```

**Comment by tombruijn** [comment]
Hi @noff, I'm having no problems unpacking my backups?

I'm on OSX and my versions are:

```
$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3

$ gzip --version
Apple gzip 242
```

Is the OS you run backup on different from the one you're unpacking it on? Try unpacking it on the server the backup was made. See if it's using the latest versions of the tools there.

Backup only uses the tools installed on your system, not any special thing we ship along with backup. You can see which tool it uses by running `which gzip` under the same user and shell as backup is configured under.

Let me know if you find out anything new.

**Comment by noff** [comment]
I'm doing it on the same server. 
Strange things, but now it works.
Will try tomorrow on fresh backup again.
Will notify.

**Comment by tombruijn** [comment]
@noff any problems with unpacking new archives?

**Comment by noff** [comment]
Hello.
Happened today:

Download archive stored using FTP
```
sftp username@hostname
Password:
sftp> cd backup/2015.07.26.09.30.20
sftp> get dbdump.tar
Fetching /backup/dbdump/2015.07.26.09.30.20/dbdump.tar to dbdump.tar
/backup/rees46/2015.07.26.09.30.20/dbdump.tar                                                                                                    100% 5709MB   9.9MB/s   09:35  
```

Untar:
```
tar xf dbdump.tar
```

Go to folder with untar'ed file
```
$ cd dbdump/databases/
$ ls -la
total 5845824
drwxr-xr-x 2 rails rails       4096 Jul 26 18:33 .
drwxr-xr-x 3 rails rails       4096 Jul 26 12:30 ..
-rw-r--r-- 1 rails rails 5986108806 Jul 26 13:19 PostgreSQL.sql.gz
```

Trying to gunzip:
```
$ gzip -d PostgreSQL.sql.gz 
gzip: PostgreSQL.sql.gz: invalid compressed data--format violated
```

It's not happens on small files. Usually I get in on large archives, but not everytime (my previous attempt few days ago was successful).

**Comment by tombruijn** [comment]
Have you tried unzipping it on the server the backup was run from? Are you unpacking it on Windows by any chance? What OS is the server running on and what OS are you trying to unpack it on?

Could the server's harddrive be full? In case the upload was incomplete? Do the logs say anything about an upload failure? Which "storage" module do you use?

**Comment by noff** [comment]
Found it is problem when I download backup using "sftp" console app.
When downloaded same file using wget in gunzipped successfully.

**Comment by tombruijn** [comment]
Do you know specifically why it doesn't work in sftp? It gets corrupted during download then?

Annoying that it happens, but glad it's not a bug in backup :) Thanks for the update!

**Comment by noff** [comment]
I think it gets corrupted during download. Asked storage service provider about it.
