### ISSUE TITLE
rotation logs?

### ISSUE THREAD

**Issue by chebyte** [backup/backup#685]
I just configure this gem and looks amazing, but it always overwrite the same backup, I want save all my backups using date m-d-y, I was looking at documentation but I cant realize it

anyone knows how can I do that?

**Comment by tombruijn** [comment]
hi @chebyte. It shouldn't overwrite the same backup. It uses timestamps for each backup. Have you not configured a sync operation instead? Can you post your config?

If you want to use a special format for your timestamped backups you can have a look in this issue how to set that up https://github.com/backup/backup/issues/641 at your own risk

**Comment by chebyte** [comment]
this is my config, it always save with the same name

````
# encoding: utf-8

##
# Backup Generated: production_backup
# Once configured, you can run the backup with the following command:
#
# $ backup perform -t production_backup [-c <path_to_configuration_file>]
#
# For more information about Backup's components, see the documentation at:
# http://backup.github.io/backup
#
Model.new(:production_backup, 'Description for production_backup') do
  compress_with Gzip

  database PostgreSQL do |db|
    db.name               = "xxxx"
    db.username           = "xxxx"
    db.password           = "-xxxx"
    db.host               = "localhost"
    db.port               = 5432
  end

  ##
  # Store on Amazon S3
  #
  store_with S3 do |s3|
    s3.access_key_id = "xxxx"
    s3.secret_access_key = "xxxx"
    s3.bucket = "neuroticket"
    s3.path = "/database"
  end
end
````

**Comment by tombruijn** [comment]
For every backup the gem creates a directory with the timestamp: `2015.07.24.04.00.04` = `yyyy.mm.dd.hh.mm.ss`. In that directory the name of your model, in your case `production_backup` is saved. So yeah, the file named is the same, but the parent directory is not.

Is it not creating the parent directory per backup?

**Comment by chebyte** [comment]
now is working fine, thanks a lot!, amazing work!
