### ISSUE TITLE
How to suppress fog warning on S3 bucket names with dots?

### ISSUE THREAD

**Issue by tisba** [backup/backup#686]
I'm wondering, how I can suppress fogs warning on S3 bucket names with dots:

> [fog][WARNING] fog: the specified s3 bucket name(mybucket.has.dots) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html

I know that this is not optimal, but I simply cannot change the bucket name right now. Is there any way to make fog ignore this particular warning?

Fog can be silenced by `Fog::Logger[:warning] = nil`, but I'm not sure if this is a good idea since it will cut of any fog warnings.

**Comment by tombruijn** [comment]
You can ignore warnings. It's described how at the bottom of this page: http://backup.github.io/backup/v4/logging/

so probably something like this:

```ruby
Logger.configure do
  ignore_warning 'fog: the specified s3 bucket name(mybucket.has.dots) contains a'
end
```

**Comment by tisba** [comment]
Thanks, that is much nicer indeed!

**Comment by brianlukoff** [comment]
I'm having the same issue and `ignore_warning` doesn't seem to suppress the messages. (I've tried both the string and regular expression forms.)

**Comment by tombruijn** [comment]
@brianlukoff what warning message do you get and how are you trying to suppress it?

**Comment by brianlukoff** [comment]
Here's an example warning:
```
[fog][WARNING] fog: the specified s3 bucket name([name omitted]) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
```

And here's the config I'm using to try to suppress:
```
Logger.configure do
  syslog.enabled    = true
  ignore_warning "fog: the specified s3 bucket name([name omitted]) contains a '.' so is not accessible over https as a virtual hosted bucket"
end
```
