### ISSUE TITLE
Question about syncers

### ISSUE THREAD

**Issue by d3sire** [backup/backup#688]
Duplicating my question from backup's chat room.

>Hi everyone! I have a question regarding syncers. From what I understand from documentation syncers sync directories to different storages after backup was made. Is there any way to sync on action? For example, when new file is uploaded it is automatically synced to an external storage. I am trying to understand what is an advantage of using syncer compared to queueing system which processes every file upload and syncs it to an external storage.

**Comment by tombruijn** [comment]
Hi @d3sire, sorry for the delay in response on gitter. My notification settings weren't set up correctly. I responded on gitter [here](https://gitter.im/backup/backup?at=55d0a7e8204de35b423051be)
