### ISSUE TITLE
Cannot install backup 4.0 with rails 4.2

### ISSUE THREAD

**Issue by Sija** [backup/backup#691]
Dependency mismatch leads to an error when installing alongside `rails 4.2`:
```
Bundler could not find compatible versions for gem "thread_safe":
  In Gemfile:
    rails (~> 4.2.3) ruby depends on
      activejob (= 4.2.3) ruby depends on
        activesupport (= 4.2.3) ruby depends on
          thread_safe (>= 0.3.4, ~> 0.3) ruby

    rails (~> 4.2.3) ruby depends on
      activejob (= 4.2.3) ruby depends on
        activesupport (= 4.2.3) ruby depends on
          tzinfo (~> 1.1) ruby depends on
            thread_safe (~> 0.1) ruby

    backup (~> 4.0) ruby depends on
      thread_safe (= 0.1.3) ruby
```

**Comment by tombruijn** [comment]
That's because you shouldn't use it in a Rails project. From the documentation:

> Using Bundler

> **Do not add `gem backup` to another application's Gemfile.** This means you **should not add Backup to a Rails** application's Gemfile. Backup is not a gem library and should not be treated as a dependency of another application. Bundler can be used to manage an installation of Backup, but the reasons for why you might want to do this is beyond the scope of this document.

> See also [this issue](https://github.com/backup/backup/issues/635) for more information.

**Comment by Sija** [comment]
That's really a bummer since this way you can't use along with capistrano... :/
Any suggestions on how to solve it another way?

**Comment by tombruijn** [comment]
@Sija why are you using it in combination with capistrano? To install it?

I recommend creating a separate project installing it separately.
