### ISSUE TITLE
Show more info in Nagios notifier message

### ISSUE THREAD

**Issue by txapelgorri** [backup/backup#694]
When the Nagios notifier sends a passive message to your Nagios host, actually looks like:

"Completed Successfully in 00:00:00"

If you have several Backup cron tasks and want more info of which one is working fine or not, it whould be very recommended to add more information to this message. Something like:

"Test files backup: Completed Successfully in 00:00:01"

I've achieved this by modifiying my local copy of Backup:
* Add "#{model.label}: " at line 63 on lib/backup/notifier/nagios.rb
but would be great to have this feature on main code :)

**Comment by tombruijn** [comment]
hi @txapelgorri! Sure we can add it. It's such a minor change. I have no experience with nagios or how such a change will look wherever this notification appears. So please let me know what the result of this change is in the form of a screenshot or something.

In the future, I recommend sending in a PR. Your change already shows you know where to look and the only thing I had to do was update the specs.

**Comment by txapelgorri** [comment]
Hi @tombruijn, nice to read your suggestions :)

Here it goes an screenshot:
![captura de pantalla de 2015-09-08 09 18 54](https://cloud.githubusercontent.com/assets/204091/9728813/f3e6c31a-560a-11e5-9ef4-3a2ac6e9f947.png)
Sorry, it's in Spanish, but the important thing is that the message has changed from "Failed in 00:02:39" to "Relevant info for me in Spanish out from model.label: Failed in 00:02:39". This way I can see in the Event log of Nagios which job exactly has failed.

Regarding PR, I tried but I couldn't: I cloned the repo, create a new branch out from master, tried to push it => failed :/

**Comment by tombruijn** [comment]
Thanks for the update and screenshot!

Weird that you couldn't push it. Your SSH keys setup correctly?

**Comment by txapelgorri** [comment]
Thank you for this great gem :) and yes, maybe that could be the problem that avoided me to push it. Next time I'll review that topic ;)
