### ISSUE TITLE
Compressor raises a warning if it tries to change to a directory it is already in

### ISSUE THREAD

**Issue by FreakyDug** [backup/backup#695]
I have a backup running as root from cron. Every time it runs, I get an email with the following warning:

```
[2015/09/08 12:18:20][warn]   Pipeline STDERR Messages:
[2015/09/08 12:18:20][warn]   (Note: may be interleaved if multiple commands returned error messages)
[2015/09/08 12:18:20][warn]
[2015/09/08 12:18:20][warn]   could not change directory to "/root"
```

As far as I can tell, this is happening because the backup is run in /root (root's home directory) and the compressor tries to change to /root as part of its operation. The change fails because it's already there and a warning gets raised.

**Comment by tombruijn** [comment]
Hi @FreakyDug, thanks for the report. Can you provide me with some more information about your config? Now I don't know exactly where to look for this. What's the command you run backup with? Any configuration flags given?

The backup itself is still completed successfully?

**Comment by FreakyDug** [comment]
Hi @tombruijn, thanks for responding. My config is:

``` ruby
    archive 'chef_backup' do |archive|
      archive.use_sudo
      archive.add '/etc/opscode'
      archive.add '/var/opt/opscode'
    end

    database PostgreSQL do |db|
      db.name = :all
      db.sudo_user = 'opscode-pgsql'
    end

    compress_with Bzip2

    store_with Local do |local|
      local.path = '/mnt/data/'
      local.keep = 5
    end
```

and my cron file contains:

```
PATH=/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0 0 * * * root  backup perform --trigger chef_backup --config-file /etc/backup/config.rb --log-path=/var/log > /dev/null
```

The backup is successful, it just produces that unnecessary warning which cron then helpfully emails to me.

**Comment by tombruijn** [comment]
Alright, then it looks like it's not your config.
I'll have a look what exactly is trying to change the directory in backup and get back to you.

**Comment by tombruijn** [comment]
Actually I see that this error most likely comes from postgresql. Since you're using the `sudo_user` option I imagine the user `opscode-pgsql` doesn't have read write access to the `/root` directory? It does have access to the `~/backup` dir?

Tip to get this to stop annoying you now: Ignore the warning message as described in [the logging documentation](http://backup.github.io/backup/v4/logging/) (very bottom of the page)

**Comment by FreakyDug** [comment]
Ah, I didn't think of that. Seems obvious now.

Ignoring the warning solves the problem for me. Thanks.
