### ISSUE TITLE
Duration in messages

### ISSUE THREAD

**Issue by overstack** [backup/backup#697]
Hi,
is it possible to add default or optional  #{ model.duration } in notification message for HipChat and HttpPost?
Thanks in advance!

**Comment by tombruijn** [comment]
Hi @overstack. Good idea, but not necessarily by default. Not everyone may want it so one personal setting could be annoying to others.

Instead I started working on a way to customize notifiers messages. Taking a bit longer than I had hoped, but you can see my progress so far in #698.

This will allow you to customize your message like so:

```ruby
notify_by HipChat do |notifier|
  notifier.message = lambda do |model, data|
    "#{ data[:status][:message] } #{ model.label } (#{ model.trigger }) - Duration: #{model.duration}"
  end
end
```

Try it out and let me know if it works for hipchat and httppost so far, those ones I have updated to use this new option.

**Comment by overstack** [comment]
It works fine, thanks.
