### ISSUE TITLE
Destination folder names

### ISSUE THREAD

**Issue by SebastianSzturo** [backup/backup#713]
I couldn't find anything in the docs and google. Is it possible to change the folder name structure?

Right now my backups get saved in 
```
/2015.03.22.06.30.15/backup.tar
```
I would like to start the backup folder name with the month, so that it would be easier to find the backups on s3.
```
/03.22.2015.06.30.15/backup.tar
```

Is that currently possible with this gem?

**Comment by tombruijn** [comment]
This isn't possible right now, but more people have asked it. My hack/workaround is here: https://github.com/backup/backup/issues/641#issuecomment-85688354

Let me know if that is what you were looking for
