### ISSUE TITLE
SFTP storage slow transfers

### ISSUE THREAD

**Issue by ukasiu** [backup/backup#715]
Transfers initiated by backup gem are painfully slow (<1Mbit/s) on 100Mbit network, consuming 100% of cpu. Normal scp transfers work correctly (full speed).

**Comment by shakycode** [comment]
What transfer method are you using?  Rsync?  Rsync has been slow for me and does peg my CPUs at times.

**Comment by ukasiu** [comment]
I'm using `Storage::SFTP`

**Comment by bdossantos** [comment]
Same issue for me, with SCP.

Does anyone also have this problem?

**Comment by leozero** [comment]
Same issue with SCP, 7mn for 256mo instead of 3 secondes with scp in command line

**Comment by stuartellis** [comment]
@leozero - Thank you for the links: that was very helpful.

I think that switching to use command makes sense, so would be happy to accept patches for that.
