### ISSUE TITLE
tar.gz in a tar file

### ISSUE THREAD

**Issue by ramonskie** [backup/backup#718]
my archives are backuped in tar format
and in that tar package there is the tar.gz
because i added the gzip compressor

so why is the compressed backup file again in a tar file
this does not make any sense to me

my model has the following
```
  compress_with Gzip
  archive :data do |archive|
    archive.add '/var/mydir'
    archive.tar_options '-p'
  end
```

**Comment by tombruijn** [comment]
So what is the actual structure of your backup file? Like so?:

```
- backup.tar
  - archives/
    - archive.tar.gz
```

That's normal. Well, that's how backup is set up. Backup performs all the separate backup procedures, archives that and compresses it. Then in the final step it archives it in one big backup file.

It makes it easier to transfer the data as one file compared to splitting it up.

**Comment by ramonskie** [comment]
Yes that's exactly the structure.
But it's annoying for restore potions because now we need several more
steps to unpack and restore
Are there any tricks to solve this?

Op do 29 okt. 2015 21:51 schreef Tom de Bruijn <notifications@github.com>:

**Comment by tombruijn** [comment]
Can't really change this now. It's how the backup pipeline works. You could write a little script for it to extract all nested files
