### ISSUE TITLE
Problem with capistrano 3.4.0

### ISSUE THREAD

**Issue by shuargan** [backup/backup#719]
Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    capistrano (~> 3.4.0) ruby depends on
      sshkit (~> 1.3) ruby depends on
        net-ssh (>= 2.8.0) ruby

    capistrano (~> 3.4.0) ruby depends on
      sshkit (~> 1.3) ruby depends on
        net-scp (>= 1.1.2) ruby depends on
          net-ssh (>= 2.6.5) ruby

So the requirde version for backup  (net-ssh (<= 2.5.2) ruby) crash with the required for capistrano

**Comment by tombruijn** [comment]
Why is capistrano part of your backup project?

See also #635 and #691

**Comment by shuargan** [comment]
Capistrano is part of my project as backup now, but having capistrano installed I cant even make backup work in a new project, i follow all the instructions of installation from the web but cant make it work, so far ill just create my own rake task and fix this issue, is not a big problem but is doing again by my own something that I can use with this gem

**Comment by shuargan** [comment]
Ive just cleanup old version and now everything is working fine, sorry for reporting an non error

**Comment by tombruijn** [comment]
This is a problem that's probably quite easily fixed by using bundler to install the gem and run it.

Good to hear it's working at least now
