### ISSUE TITLE
Old backups not getting removed

### ISSUE THREAD

**Issue by amnesia7** [backup/backup#722]
I have the following in my model (that is called by a cron job run at midnight):
```
  time = Time.now
  if time.day == 1  # first day of the month
    storage_id = :monthly
    keep = 6
  elsif time.sunday?
    storage_id = :weekly
    keep = 3
  else
    storage_id = :daily
    keep = 12
  end

  ##
  # Local (Copy) [Storage]
  #
  store_with Local do |local|
    local.path       = "/backups/#{ storage_id }"
    local.keep       = keep
  end
```
I've been getting multiple warning messages about folders not being there in an email that seems to coincide with the weekly backup running. Here's an example of one of the warnings:
```
[2015/11/22 05:01:13][info] Removing backup package dated 2015.11.18.05.01.12...
[2015/11/22 05:01:13][warn] Storage::Cycler::Error: There was a problem removing the following package:
[2015/11/22 05:01:13][warn]   Trigger: my_backup :: Dated: 2015.11.18.05.01.12
[2015/11/22 05:01:13][warn]   Package included the following 1 file(s):
[2015/11/22 05:01:13][warn]   my_backup.tar
[2015/11/22 05:01:13][warn] --- Wrapped Exception ---
[2015/11/22 05:01:13][warn] Errno::ENOENT: No such file or directory - /some-folder/backups/weekly/my_backup/2015.11.18.05.01.12
```
I've just had a look and the older backups don't seem to be getting removed.

There are loads in the `daily` folder.

There are 7 folders in the `monthly` folder (the backup facility has been running for about 7 months) folders so I think one of these should've been removed/tidied up. 

The `weekly` folder only had 3 folders in it but they weren't the last 3 sundays as I expected. One was this sunday just gone, one was in October and the third was in April when I put the backup facility in place. I've been getting the weekly warning message email since April but have only just got around to looking into it.

Am I missing something here?

**Comment by tombruijn** [comment]
I think you may have forgotten to set the `storage_id` on the `store_with` declaration.

As described on this page: http://backup.github.io/backup/v4/storages/

```
time = Time.now
if time.day == 1  # first day of the month
  storage_id = :monthly
  keep = 6
elsif time.sunday?
  storage_id = :weekly
  keep = 3
else
  storage_id = :daily
  keep = 12
end

store_with Local, storage_id do |sftp|
  # ..
end
```

If you don't do this the records of every type of backup (monthly, weekly, daily) get mixed up in the database backup keeps. Then it goes on to remove the `keep` amount for that type of backup regardless of what type they are.

**Comment by amnesia7** [comment]
Thanks @tombruijn I've updated the backup file so hopefully that'll sort it. 
I'll close the issue and re-open again if it doesn't.
