### ISSUE TITLE
Error: option 'datadir' has different values when using innobackupex:

### ISSUE THREAD

**Issue by ramonskie** [backup/backup#723]
when using innobackupex i get the following error

```
Error: option 'datadir' has different values:
  '.' in defaults file
  '/var/lib/mysql/' in SHOW VARIABLES
```

so i think it would be nice to be able to set the defaults-file option
see https://www.percona.com/doc/percona-xtrabackup/2.1/innobackupex/creating_a_backup_ibk.html

**Comment by tombruijn** [comment]
You should be able to set the defaults-file option. Have you tried `additional_options = ["--your-option=value-here"]` on the mysql database config?
