### ISSUE TITLE
Atomic 1.1.14 error

### ISSUE THREAD

**Issue by arazumoff** [backup/backup#726]
Hey every one! I have a trouble from install

gem install backup
Fetching: CFPropertyList-2.3.1.gem (100%)
Successfully installed CFPropertyList-2.3.1
Fetching: addressable-2.3.5.gem (100%)
Successfully installed addressable-2.3.5
Fetching: atomic-1.1.14.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing backup:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
creating Makefile

make "DESTDIR=" clean
sh: 1: make: not found

make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /var/lib/gems/2.1.0/gems/atomic-1.1.14 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/atomic-1.1.14/gem_make.out

**Comment by tombruijn** [comment]
Can you install `gem install atomic` itself? See if you can actually install that gem and if you have all the required dependencies installed

**Comment by arazumoff** [comment]
Unfortunately, the same mistake.

gem instal atomic
Building native extensions.  This could take a while...
ERROR:  Error installing atomic:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.1.0/gems/atomic-1.1.99/ext
/usr/bin/ruby2.1 -r ./siteconf20151211-8030-cr7rls.rb extconf.rb
checking for libkern/OSAtomic.h... no
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/atomic-1.1.99/mkmf.log

current directory: /var/lib/gems/2.1.0/gems/atomic-1.1.99/ext
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /var/lib/gems/2.1.0/gems/atomic-1.1.99/ext
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /var/lib/gems/2.1.0/gems/atomic-1.1.99 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/atomic-1.1.99/gem_make.out

**Comment by tombruijn** [comment]
Aha! Well good to hear it works now :smile:
