### ISSUE TITLE
How to create hipchat api v2 support?

### ISSUE THREAD

**Issue by pskrz** [backup/backup#733]

**Comment by radriaanse** [comment]
Not sure if I understand you correctly, but Hipchat v2 is already available trough the config option;
`hipchat.api_version = 'v2'`. So for example:

    Notifier::Hipchat.defaults do |hipchat|
       hipchat.on_success      = true
       hipchat.on_warning      = true
       hipchat.on_failure      = true

       hipchat.success_color   = 'green'
       hipchat.warning_color   = 'yellow'
       hipchat.failure_color   = 'red'

       hipchat.token           = 'TOKEN_HERE'
       hipchat.from            = ''
       hipchat.rooms_notified  = ['ROOM_ID_HERE']
       hipchat.api_version     = 'v2'
    end
