### ISSUE TITLE
Support multiple configuration files to seperate passwords from preconfigured models

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [backup/backup#734]
Hi,

first of all: thanks for your great work. It's really a pleasure to make backups with the backup gem!

And here is my question/usecase: 

I have a repository with my code (and multiple backup configs, f.e. hourly, daily, weekly, monthly, each of them with some minor adjustments), and some servers which are build/provisioned with salt..

Since there is only support for one config file, it makes it quite hard to:

1) deploy backup-config with salt, which includes SMTP/DB-passwords (pwd file stored locally or on salt master)
2) use preconfigured models (code should stay in repository! passwords are deployed with salt)
3) use custom models with preconfigured background (code also stays in repository)

I'm not sure if my description is easy to understand, so here is it a bit shorter: i would like to seperate the passwords from the preconfigured models - but at the moment both of them stay in the same file, so its harder to seperate the passwords file (locally) from the model configuration (repository).

If you would support multiple configs like

``` shell
backup perform --trigger myconfig_monthly --config_file file1.conf  --config_file file2.conf 

# or maybe something like this
backup perform --trigger myconfig_monthly --config_file file1.conf  --preconfig_models preconfig_models.conf 

# or maybe something like this
backup perform --trigger myconfig_monthly --config_file file1.conf  --password_file passwords.conf 
```

it would be really great..

What do you think?

Thanks!

**Comment by tombruijn** [comment]
I can't say that I follow. You're trying to have a different configuration (passwords) per model? but want to configure this on the preconfigured models?

Every model is it's own config, so configure everything there. You don't have to use the config.rb file to configure any preconfigured thing.

Adding more configuration options will get confusing I think.
