### ISSUE TITLE
Support for configuring the backup folder name instead of using the trigger/model name.

### ISSUE THREAD

**Issue by deepak07** [backup/backup#738]
I have different models which follows the name format as give below for postgres backup (daily/weekly/monthly basis). 

* project_1_daily.rb
* project_1_weekly.rb
* project_1_monthly.rb

When the database backup is done and is uploaded to S3, it takes the model/trigger name as directory name. It is stored in S3 like this -->

- daily
  - project_1_daily
    - 2016.02.04.08.50.26
      - project-1.tar
- weekly
  - project_1_weekly
    - 2016.02.04.08.50.26
      - project-1.tar

The daily, weekly are the folders with which I am trying to organise s3 uploads.

In the code lib/backup/database/base.rb, dump_path is set without any configurable options.
`def initialize(model, database_id = nil)`
`  @model = model`
`  @database_id = database_id.to_s.gsub(/\W/, '_') if database_id`
`  @dump_path = File.join(Config.tmp_path, model.trigger, 'databases')`
`  load_defaults!`
`end`
Will that be possible to have a configurable name for the folder created on backup instead of taking the model.trigger name. 

_Awesome work on the gem guys. Thanks for it._

**Comment by tombruijn** [comment]
Hi, it's not really possible. The model trigger is used all over the place as a basis for the storage path. So I wouldn't really know how to support that.

Perhaps you can override the method on storage/base as a workaround, but I can't guarantee anything. https://github.com/backup/backup/blob/0c7eb22c7b5b8e3f67e0974836eecc9a99a95276/lib/backup/storage/base.rb#L56-L59

**Comment by deepak07** [comment]
I hoped so :) .. I went through the code and it seems a major workaround for adding a custom naming..
