### ISSUE TITLE
Mail timeout using Mandrill server

### ISSUE THREAD

**Issue by daigo75** [backup/backup#739]
I configured the Mail parameters to use Mandrill (all parameters tested manually, they are correct), and the email step always times out. There aren't many details, just the following message:

```
ModelError: Backup::Notifier::Mail Failed to send notification of backup failure.
  Reason: Timeout::Error
```

Do I have to do something specific to use Mandrill with the Mail gem?

Thanks in advance for the information.

**Comment by tombruijn** [comment]
you're using the mail notifier? Should work from backup. Have you tried setting up a small mail test from outside backup on the same server? (Backup uses the mail gem for mail notifications.) That way you'll know if it's the server or backup. Check if your firewall isn't blocking it, for example

**Comment by daigo75** [comment]
I also expected it to work normally, but it doesn't. Testing the same parameters via a small PHP script works fine (I have little to no knowledge of Ruby, but I don't think it makes a difference).

I worked around the issue using sendmail, for the moment it's ok.
