### ISSUE TITLE
Is there a way to "tag" backups?

### ISSUE THREAD

**Issue by daigo75** [backup/backup#740]
I was wondering if there is a way to "tag" backups, perhaps with a comment, to distinguish more easily which ones were created for a specific purpose (e.g. before a major upgrade), in comparison to the automated ones. Is there a way do that?

**Comment by tombruijn** [comment]
not really. What would you have in mind? something at the end of a backup file name? Currently we don't support custom file names

**Comment by daigo75** [comment]
I wasn't necessarily thinking of file names. ZIP files, for example, support custom meta (they have a `description` meta of some sort). I was wondering if the same could be used for the gzipped files (zip, gzip, perhaps they have the same features).

**Comment by imcookie** [comment]
Really good idea, to add some meta information, like "before adding some feature"
