### ISSUE TITLE
Ubuntu 14.04 - The program 'backup' is currently not installed

### ISSUE THREAD

**Issue by joaomarcelo9393** [backup/backup#741]
I can't run backup commands after installing the gem. I am using RVM and Ubuntu. Any ideas?

    $ gem install backup
    $ backup help generate:model
    > The program 'backup' is currently not installed. You can install it by typing:
    > sudo apt-get install openafs-client

**Comment by kujiy** [comment]
I installed it just now.
I had the `backup` here on ubuntu 14 with rvm and ruby 2.1.5.

```bash
root@817819f4a220:~# which backup
/root/.rvm/gems/ruby-2.1.5/bin/backup
```

Was your gem installer worked exactly?
I got these message below after excute the install command.

```
root@817819f4a220:/# gem install backup
Fetching: addressable-2.3.5.gem (100%)
Successfully installed addressable-2.3.5
Fetching: atomic-1.1.14.gem (100%)
Building native extensions.  This could take a while...
... 
Installing ri documentation for unf-0.1.3
Parsing documentation for backup-4.2.2
Installing ri documentation for backup-4.2.2
Done installing documentation for addressable, atomic, builder, mime-types, polyglot, treetop, mail, xml-simple, aws-ses, buftok, CFPropertyList, descendants_tracker, json, dogapi, dropbox-sdk, equalizer, excon, multipart-post, faraday, fission, multi_xml, httparty, multi_json, flowdock, formatador, net-ssh, net-scp, fog-core, mini_portile, nokogiri, fog-xml, fog-atmos, fog-json, ipaddress, fog-aws, inflecto, fog-brightbox, fog-ecloud, fog-profitbricks, fog-radosgw, fog-riakcs, fog-sakuracloud, fog-serverlove, fog-softlayer, fog-storm_on_demand, fog-terremark, fog-vmfusion, fog-voxel, fog, hipchat, http_parser.rb, http, thread_safe, memoizable, net-sftp, open4, pagerduty, simple_oauth, thor, twitter, unf_ext, unf, backup after 96 seconds
63 gems installed
root@817819f4a220:/# 
```

What did your gem intaller say?

**Comment by joaomarcelo9393** [comment]
Ok, it just worked this morning. I don't understand why. I repeated installation a couple of times yesterday with no success. Maybe the reboot solved whatever the issue was? Thank you anyway.

**Comment by tombruijn** [comment]
It was probably a PATH issue. Check if the directory that backup is installed in is present in `echo $PATH`

**Comment by joaomarcelo9393** [comment]
It is there now. If I remember correctly, it wasn't there yesterday and I added  `home/myuser/.rvm` to `.bashrc` or `.bash_profile`. But the correct path is `/home/myuser/.rvm/gems/ruby-2.2.1/bin` -- that is where `which backup` points to, and it is there now. Do you need to source the $PATH or something alike after adding a new path?

**Comment by kujiy** [comment]
Hi there. I remembered that I had to execute `source /etc/profile` after installing backup with `gem install backup`.
If I didn't do it, the `backup` command was not found.

BTW, my server said `backup command not found` this morning. I re-installed it then worked.
I don't know why...

For anothrer information, `backup` is here on my Cent OS 7 with rvm.
```
# on Cent OS 7
[root@docker01 Backup]# which backup
/usr/local/rvm/gems/ruby-2.2.1/bin/backup
```

**Comment by tombruijn** [comment]
I see you're using rvm and it should be responsible for setting the PATH for gems installed. If backup cannot be found the path has not been set (correctly) by rvm. Check if your ruby version is the default and if it's set correctly by whatever user calls the (hopefully) automated backup task .
