### ISSUE TITLE
Backup fails when trying to upload second manifest file to Rackspace Cloudfiles

### ISSUE THREAD

**Issue by russjohnson** [backup/backup#742]
Our setup has been in place for a year now and has been working flawlessly. 2 days ago our hourly backups started failing while uploading the manifest files. Ive included a sanitized version of our model and attached a text file of one of the logs we receive from the backup failure.

In the log it mentions leftover tmp files so I have tried manually removing those before the next backup with no luck. 

The actual error is saying that the second manifest files haplatform_backup.tar-aab doesnt exist :

```
[2016/02/10 17:21:23][info] Storing 'dbbackups/haplatform_backup/2016.02.10.16.00.03/haplatform_backup.tar-aab'...
[2016/02/10 17:21:23][error] Model::Error: Backup for HomeActions platform (haplatform_backup) Failed!
[2016/02/10 17:21:23][error] --- Wrapped Exception ---
[2016/02/10 17:21:23][error] Errno::ENOENT: No such file or directory @ rb_file_s_size - /home/deployer/Backup/.tmp/haplatform_backup.tar-aab
```

However when I check that path, that file does in fact exist. The first manifest file is there as well as the second manifest file which it complains about. Apparently the first one is getting uploaded but failing on the second.

Model config below:

```
Model.new(:haplatform_backup, 'Platform Backup') do
  split_into_chunks_of 5000
  compress_with Gzip

  ##
  # PostgreSQL [Database]
  #
  database PostgreSQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name               = "xxxxxxxx"
    db.username           = "xxxxxxxx"
    db.password           = "xxxxxxxx"
    db.host               = "xxxxxxxx"
    db.port               = xxxxxxxx
    db.additional_options = ["-xc", "-E=utf8"]
  end

  ##
  # Rackspace Cloudfiles Store
  #
  store_with CloudFiles do |cf|
    cf.api_key            = 'xxxxxxxx'
    cf.username           = 'xxxxxxxx'
    cf.container          = 'dbbackups'
    cf.segments_container = 'dbbackup_segments_container' # must be different than `container`
    cf.segment_size       = 5 # MiB
    cf.path               = '' # path within the container
    cf.servicenet = true
    cf.days_to_keep = 14
    cf.max_retries = 10
    cf.retry_waitsec = 30
    cf.fog_options = {
    :persistent => true,
    :connection_options => { :family => ::Socket::Constants::AF_INET,
                :connect_timeout => 360,
                    :read_timeout => 360,
                    :write_timeout => 360 }
    }
  end

  ##
  # Mail [Notifier]
  #
  # The default delivery method for Mail Notifiers is 'SMTP'.
  # See the documentation for other delivery options.
  #
  Removed for sanitation

end
```

Log file:
[logfile.txt](https://github.com/backup/backup/files/126759/logfile.txt)

**Comment by russjohnson** [comment]
Wondering now if this could be a timing thing... If the current backup takes longer than an hour to run and finish uploading, could the next job starting at top of the hour be wiping the temp manifest files before the previous job has a chance to upload them?

**Comment by russjohnson** [comment]
After more testing, this seems to be the case. The backup job takes longer to upload than an hour so the next backup job is deleting the temp files and cleaning up before its run. 

With this being the case, is there someway to prevent it from cleaning up the files and creating new ones with different suffixes?

**Comment by tombruijn** [comment]
There's no easy way to change the prefix per backup. It's already prefixed per model. A model backup can only run one at a time. So perhaps set it to a higher interval, every 1.5 hours or so.
