### ISSUE TITLE
NoMethodError: undefined method `i' when running as Cron

### ISSUE THREAD

**Issue by daigo75** [backup/backup#744]
I noticed today that the backup script I configured works fine when I run it manually (`backup perform`), but the notification is not sent when it runs as part of a cron task. The error message is the one in the subject, here in more detail:

~~~
[2016/02/17 09:00:02][error] CLI::Error
[2016/02/17 09:00:02][error] --- Wrapped Exception ---
[2016/02/17 09:00:02][error] NoMethodError: undefined method `i' for #<Backup::Notifier::Mail:0x2b27d4482138>
~~~

I don't know what "i" means, it's an obscure message.

Here's the related section from the model configuration:.
~~~
  notify_by Mail do |mail|
    mail.on_success           = true
    mail.on_warning           = true
    mail.on_failure           = true

    mail.delivery_method      = :sendmail
    mail.from                 = "sender_email@aelia.co"
    mail.to                   = "target_email@aelia.co"
  end
~~~

**Comment by tombruijn** [comment]
Hi @daigo75, do you have a stacktrace for the error? In the log for example

**Comment by daigo75** [comment]
I didn't configure the Logger module, all I have at the moment is this:

~~~
[2016/02/17 09:00:02][error] CLI::Error
[2016/02/17 09:00:02][error] --- Wrapped Exception ---
[2016/02/17 09:00:02][error] NoMethodError: undefined method `i' for #<Backup::Notifier::Mail:0x2b27d4482138>
~~~

There's an interesting development, though: the backup script, which worked perfectly when I ran it manually, now fails with the same error. The scripts are the same I used until a couple of days ago, they haven't been changed, but now they crash with that cryptic error message.

**Comment by daigo75** [comment]
If it may help, the issue doesn't seem to be related to the models themselves. I tried running a test model I created when I first installed the backup script, which doesn't run the Mail module, and it crashes straight away.

**Comment by daigo75** [comment]
Is there a way to print out a full stack trace, instead of just a couple of lines? It's clear to me that there is a crash in the backup script itself (for reason unknown, it worked fine until a couple of days ago, and I haven't touched it).

I have zero knowledge of Ruby, unfortunately, therefore I would rather not fiddle with the files if possible. If there is a global "debug" flag, I could enable it to get the stack trace.

By the way, I'm running the script v3.11. I can't run v4 because the server uses CentOS 6 and it only has Ruby 1.8.7 on it.

**Comment by daigo75** [comment]
I think I found a way to get a backtrace. Here's what I got.

~~~
/home/srv296/Backup/config.rb:67:in `load_config!': undefined method `i' for #<Backup::Notifier::Mail:0x7faa276fef40> (NoMethodError)
        from (eval):83:in `load_config!'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/notifier/mail.rb:123:in `instance_eval'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/notifier/mail.rb:123:in `initialize'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/model.rb:186:in `new'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/model.rb:186:in `notify_by'
        from (eval):78:in `load_config!'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/model.rb:127:in `instance_eval'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/model.rb:127:in `initialize'
        from (eval):9:in `new'
        from (eval):9:in `load_config!'
        from /home/srv296/Backup/config.rb:66:in `each'
        from /home/srv296/Backup/config.rb:66:in `load_config!'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/lib/backup/cli.rb:139:in `perform'
        from /home/srv296/.gem/ruby/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `__send__'
        from /home/srv296/.gem/ruby/1.8/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/srv296/.gem/ruby/1.8/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/srv296/.gem/ruby/1.8/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/srv296/.gem/ruby/1.8/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/srv296/.gem/ruby/1.8/gems/backup-3.11.0/bin/backup:5
        from /home/srv296/.gem/ruby/1.8/bin/backup:19:in `load'
        from /home/srv296/.gem/ruby/1.8/bin/backup:19
~~~

**Comment by daigo75** [comment]
Got it

**Comment by daigo75** [comment]
Then my colleagues wonder why I always double check everybody else's work... :smile:
