### ISSUE TITLE
Storing with CloudFiles using days_to_keep and Local using keep does not cycle local packages

### ISSUE THREAD

**Issue by cgunther** [backup/backup#745]
I have my model configured to store both locally (via Local) and remotely (via CloudFiles), keeping the last 7 packages locally and for 30 days remotely. The remote packages "cycle" fine as Rackspace is handling it directly, however the local packages do not cycle.

Looking in the YAML data file for this model and the Local storage, I see each package has `no_cycle: true`, which prevents the package from being removed (https://github.com/backup/backup/blob/c63ac95ba778fc3d825a516d70070a0c154d55a4/lib/backup/storage/cycler.rb#L36). It would appear `no_cycle: true` is set because the CloudFiles storage is using `days_to_keep` (https://github.com/backup/backup/blob/42cb46fcf4b2aa352f8e5899095ec086d9b20ec4/lib/backup/storage/cloud_files.rb#L115).

I'm assuming I could switch the CloudFiles storage to use `keep` instead of `days_to_keep` and let the gem handle the cycling, but is there a preferred way to configure CloudFiles and Local storage simultaneously in a single model using `days_to_keep`? Perhaps the `no_cycle: true` configuration for packages should be set per-storage, so cycling is skipped for CloudFiles but not Local in this scenario.

My config looks like:

``` ruby
store_with CloudFiles do |cf|
  # ...
  cf.days_to_keep = 30
  # ...
end

store_with Local do |local|
  # ...
  local.keep = 7
  # ...
end
```

I'm using v4.2.2 of the gem and looking at the changelog of v4.2.3 I don't see any changes that would affect this behavior.

Thanks for your time and thank you for backup, it's a wonderful tool.

**Comment by max-allan-surevine** [comment]
I suggest a fix in my similar ticket.
https://github.com/backup/backup/issues/815
Add a manual "package.no_cycle = false" to local storage. _BUT_ I don't know what else that could break!
