### ISSUE TITLE
Incorrect file extension while doing PostgreSQL Backup

### ISSUE THREAD

**Issue by umate** [backup/backup#754]
Trying to do backup of PostgreSQL database with specific keys:
```ruby
db.additional_options = ["-x", "-O", "-F tar"]
```
Results in incorrect file name in the backup. It says it's **.sql**, but the file is actually a **.tar**
This happens because of hardcoded file extension in:
[https://github.com/backup/backup/blob/c63ac95ba778fc3d825a516d70070a0c154d55a4/lib/backup/database/postgresql.rb#L56](https://github.com/backup/backup/blob/c63ac95ba778fc3d825a516d70070a0c154d55a4/lib/backup/database/postgresql.rb#L56)
```ruby
dump_ext = 'sql'
```

**Comment by tombruijn** [comment]
Hi @umate, thanks for spotting this. Backup cannot detect which format you're outputting towards. So, I'm not sure how we can remedy this. If you're already using a compressor, you could also leave it out as it's archived as well then.

Let me know

**Comment by umate** [comment]
@tombruijn this totally makes sense. But I think it's worth mentioning in the documentation at least to save someone's time.

**Comment by tombruijn** [comment]
I'm not really sure how to document this, because it's a postgres option not a backup option. The configuration is called `additional_options` because backup is configured by first party configuration options first. It allows for extra options, but it has no way of knowing the impact.
