### ISSUE TITLE
Support for PostgreSQL pg_basebackup

### ISSUE THREAD

**Issue by alexef** [backup/backup#758]
Currently, backup support PostgreSQL databases backup via pg_dump utility.

For backups that can be used for PITR, there is a different tool, called pg_basebackup (http://www.postgresql.org/docs/9.4/static/app-pgbasebackup.html)

I would like to add support for this type of backups, but a I need some guidance regarding how it should be added to the codebase: as a different database backup provider, or as an option to the existing postgresql.

**Comment by alexef** [comment]
We've found this workaround, in `config.rb`:

    Utilities.configure do
       pg_dumpall '/usr/bin/pg_basebackup'
    end
and in the model: 

    database PostgreSQL do |db|
      db.sudo_user = 'postgres'
      db.additional_options = ['-D -', '-Ft']
    end

It seems to work fine, although the performance is a bit lower than just using `pg_basebackup -D /path -Ft -z`. Any hints on when can the performance be improved?

**Comment by tombruijn** [comment]
Hi @alexef, not really sure what would cause the performance to be lower. It can be the pg_basebackup tool itself, the amount of data backup has to process. You can narrow down if the problem is with backup by running it on the command line outside backup.
