### ISSUE TITLE
RethinkDB support

### ISSUE THREAD

**Issue by gokaygurcan** [backup/backup#759]
Hello, 
It'd be nice to have an option to export @RethinkDB databases as well.

They already have a [gem](https://rubygems.org/gems/rethinkdb/versions/2.2.0.3) and a useful [dump](https://rethinkdb.com/docs/backup/) command. 

I'm not that much experienced in Ruby language, but if no-one wants to add this feature, I can pick it up and try to implement. Please feel free to share your opinions.

Thanks in advance.

**Comment by tombruijn** [comment]
Hi @gokaygurcan, I personally have no experience with RethinkDB. So far it's the first mention in the backup repository. If you think that the gem benefits from this option I welcome a PR

**Comment by gokaygurcan** [comment]
Woah, so many things've changed since then. RethinkDB [shut down](https://rethinkdb.com/blog/rethinkdb-shutdown/) some months after I created this issue, then [joined](https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation) to Linux Foundation, its community almost left entirely. Phew, major events.. 
I still like to use it to hack something together but I don't think any sane person would build something with it at this stage. 

It makes me sad, that's for sure, but I'm closing the issue because it's not relevant anymore.

Thanks!
