### ISSUE TITLE
Installation Issue - CentOS 7

### ISSUE THREAD

**Issue by danfoxley** [backup/backup#767]
Can someone point me in the right direction for this error?

[gem install backup - error.txt](https://github.com/backup/backup/files/233083/gem.install.backup.-.error.txt)

**Comment by danfoxley** [comment]
Well, let me answer my own question...
Seems this got me up and running. I'm guessing I ran other w/o sudo but as root.

hostmachine ~]$
sudo yum install ruby ruby-devel gcc gcc-c++ make automake autoconf zlib*
#Installed both with and w/o sudo  
gem install backup
sudo gem install backup

**Comment by tombruijn** [comment]
Hi @danfoxley, this is not a backup installation issue, but the native extensions for nokogiri. Glad to see that you were able to install it. It's correct you have to install certain packages before you can install it.
