### ISSUE TITLE
Mysql over ssl

### ISSUE THREAD

**Issue by simonhutchings** [backup/backup#770]
Great gem, i use it for all apps. Only problem I've just come up again, is on google cloud i connect to the db over ssl. How can you set up the connection in Backup Gem?

normal connection in rails app you add the certs, any way to do this?
  sslkey: /etc/certificates/google-test-sql/client-key.pem
  sslcert: /etc/certificates/google-test-sql/client-cert.pem
  sslca: /etc/certificates/google-test-sql/server-ca.pem
  sslcapath: /etc/certificates/google-test-sql/certificates

**Comment by tombruijn** [comment]
Hi @simonhutchings, yes you can. You can use the `additional_options` configuration option to configure SSL options for mysqldump:

For more information see http://backup.github.io/backup/v4/database-mysql/ and the mysqldump documentation.

Let me know if it works out
