### ISSUE TITLE
Best Way To Implement - Keep 104 Weeks, 60 Months, 10 Years

### ISSUE THREAD

**Issue by danfoxley** [backup/backup#774]
What is the best way to configure, keep 104 Weeks, 60 Months, 10 Years?  Running three separate backup Models, or can it be rolled into a single Model?

Thanks,
Dan

**Comment by tombruijn** [comment]
Hi @danfoxley, It can be rolled into one model. You can find an example at the bottom of this page: http://backup.github.io/backup/v4/storages/
