### ISSUE TITLE
S3 sync (and others i presume) recalculates all checksums every sync

### ISSUE THREAD

**Issue by katbyte** [backup/backup#775]
I am using the backup gem to manage ~1.5 TB of backups. Each time the s3 syncer starts it recalculates all the checksums and takes hours upon hours to do so.

The local backups don't ever change and it seems like there should be a better way.

**Comment by tombruijn** [comment]
Hi @katbyte, sorry to hear that. I can imagine the larger the backup the slower it becomes. I don't think that's where the performance will be great in Ruby with such large backups.

But you say that it performs checksums for local backups? You mean the synced directories?

**Comment by katbyte** [comment]
Yes, each time the sync runs it recalculates all the checksums of the local files synced as the checksums are not stored anywhere.

This is also dangerous in that if an old backup gets corrupted it will then be blindly uploaded to s3 wiping out the valid one.

**Comment by alepore** [comment]
But local files can change in some situations (like mine, i sync images), how to store md5 checksums and invalidate the cache on file change?

**Comment by tombruijn** [comment]
@katbyte how do you mean an old backup gets corrupted? It recalculates the checksum of the local file to compare it to the s3 remote, right? If anything changes to a file on the backup server, the file gets backup-ed to s3.

@alepore I don't think you can right now.

**Comment by katbyte** [comment]
its been a while but what I thought would happen was:

1) backup synced -> s3
2) local backup is garbled and ruined
3) garbled backup is synced to s3 because the checksum changed
