### ISSUE TITLE
Support for Postgres pg_dump --format

### ISSUE THREAD

**Issue by Owumaro** [backup/backup#777]
`pg_dump` has a `--format` option (see [pg_dump man](https://www.postgresql.org/docs/9.3/static/app-pgdump.html)).

The backup gem uses its default value (`plain`) to generate sql dumps, however it would be nice to be able to set it. For example, with the `tar` format, you can then easily restore the dump using the `pg_restore` tool.
With a .sql dump, you have to untar manually, and then use `psql` to restore the dump. You also miss some features like `pg_restore -c` which allows to clean the database before restoring (there is no equivalent with `psql`).

**Comment by tombruijn** [comment]
Hi @Owumaro, you should be able to use the `additional_options` option to set any pg_dump options you want to pass along

```ruby
db.additional_options = ["--format ###"]
```

**Comment by Owumaro** [comment]
Yup, however the file will be put in `databases/PostgreSQL.sql`, which isn't very clean as it isn't made of sql statements (it should be a .dump or .backup file).

**Comment by tombruijn** [comment]
If that's something you want to support a new `format` option should be added to the postgres database configuration. Based on all supported values backup would be able to set another extension.
I'm not going to add this, but I'd be happy to review a PR
