### ISSUE TITLE
Cron Job Problem (Sudo)

### ISSUE THREAD

**Issue by dyrnade** [backup/backup#786]
Hello, i had a problem about cron job of backup. I wrote a cron job to backup my postgres db. The cron job is for root user.However, the job never worked. I spent almost 3 hours and at the end i figured it out the problem which is (i certainly specified the user(root) to run cron job) sudo. To run backup , it needs sudo , even you specify root. Its non-sense.

I don't know why this happens but i wanted to let you know guys.

Thank you.

**Comment by tombruijn** [comment]
Hi @dyrnade, I don't have that particular problem. It all depends on how your ruby is installed, the backup gem is installed, under what user and with sudo or not.

So if configured correctly, everything installed under a non sudo user, you should be able to run it without sudo just fine.
