### ISSUE TITLE
Fixed Version RubyGem dependencies needed?

### ISSUE THREAD

**Issue by maxigs** [backup/backup#789]
I'm just upgrading the backup gem i'm using as part of a RubyOnRails project.

Unfortunately this seems impossible since i have some version conflicts, due to the hard-version requirements of the backup gem.

Is there a reason these are all specific, like bad experiences in the past with version changes?
Since it requires a whole lot of gems this makes it very cumbersome trying to get the rest of the project to match it.

I will probably remove it as part of the rails project and have it run in it's own bundle now.

**Comment by tombruijn** [comment]
Hi @maxigs, you shouldn't really use backup inside a rails project. We do not update dependencies for compatibility with Rails. For more information see http://backup.github.io/backup/v4/installation/ and issue #635, along with the linked issues, where this is discussed
