### ISSUE TITLE
Add S3 region cn-north-1

### ISSUE THREAD

**Issue by fengye87** [backup/backup#791]
Hi, I was trying to use Backup to backup my db to S3. Unfortunately, we're using China's partition of AWS (region `cn-north-1`), which is slightly different than the global one. When I run the backup task, I got the following error:

```text
$ backup perform -t my_backup
...
[2016/08/03 06:36:10][info] --- Wrapped Exception ---
[2016/08/03 06:36:10][info] Excon::Errors::SocketError: getaddrinfo: Name or service not known (SocketError)
...
```

My guess is China's partition of AWS is using a different domain name (`http://www.amazonaws.cn/`) than the global one. Apparently, you won't find `cn-north-1` in the global domain.

FYI, I do find the official `aws-sdk` gem is currently working for this special region. Maybe it has got a more updated partition/region list.

**Comment by tombruijn** [comment]
Hi @fengye87 , sorry to see it's not available directly. I looked at fog-aws (the lib we use for s3 support) and it's not available there either. Someone in [this issue](https://github.com/fog/fog-aws/issues/25#issuecomment-166215438) posted endpoint config which might work.

```ruby
store_with S3 do |s3|
  s3.access_key_id     = "my_access_key_id"
  s3.secret_access_key = "my_secret_access_key"

  # s3.region # don't call it or set to: nil

  s3.fog_options = { endpoint: "https://s3.cn-north-1.amazonaws.com.cn" }
end
```

Let me know if that worked

**Comment by tombruijn** [comment]
Oh yeah, and I will close the issue as it's not a backup gem specific problem

**Comment by fengye87** [comment]
Ah yeah, it worked, with one slight fix to add:

```ruby
store_with S3 do |s3|
  s3.access_key_id     = "my_access_key_id"
  s3.secret_access_key = "my_secret_access_key"

  s3.region = "cn-north-1"
  s3.fog_options = { endpoint: "https://s3.cn-north-1.amazonaws.com.cn" }
end
```

Setting `s3.region` to `nil` or wrong value will cause AWS complaining about *Malformed Authorization Header*.

Thanks you for the help :)

**Comment by tombruijn** [comment]
Great! I'll added it to the docs in commit 540a6831f7a0c479fcf09da82e4a3adc0b3f44f6
