### ISSUE TITLE
S3 storage class STANDARD_IA not supported

### ISSUE THREAD

**Issue by christianl** [backup/backup#792]
The gem supports standard and reduced redundancy storage classes, but standard_ia (which is cheaper and probably more suited for backups, and currently cheaper than RRS) is not supported. See https://aws.amazon.com/s3/storage-classes/

**Comment by tombruijn** [comment]
Hi @christianl , it's supported. Support was added in #725, but it's not mentioned in the docs. I'll do that now

**Comment by tombruijn** [comment]
Updated in https://github.com/backup/backup/commit/f9502eb34854f96bf83b836aab977809f8dbb122
