### ISSUE TITLE
Add xz as a standard Compressor

### ISSUE THREAD

**Issue by gdubicki** [backup/backup#795]
xz is a better compressor than bzip2 in many cases. I propose to add it to backup as one of the standard Compressors.

**Comment by gdubicki** [comment]
This should probably be moved to https://github.com/backup/backup-features . Sorry, I haven't noticed that repo before.

**Comment by tombruijn** [comment]
Hi @gdubicki you can already really easily add another compression method http://backup.github.io/backup/v4/compressor-custom/
