### ISSUE TITLE
Cannot install backup after upgrade to rails 4.2.7.1

### ISSUE THREAD

**Issue by KateWilkins** [backup/backup#797]
Upgraded from ruby 2.2.3 to 2.3.1 and rails from 4.2.5 to 4.2.7.1 and now backup will not install and fails with:

[root@callisto]# gem install backup
ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
    The user requires backup (= 4.3.0) but it conflicted:
  Activated excon-0.44.4 instead of (~> 0.49) via:
    fog-core-1.42.0, fog-1.28.0, backup-4.3.0
  Activated excon-0.44.4 instead of (~> 0.49) via:
    fog-core-1.42.0, fog-1.28.0, backup-4.3.0

I've done a bundle clean and re-installed but still its breaking. Previously it was all working flawlessly with 4.3.0. The app itself is still working fine, the normal bundle install works without error.

Help!
Any ideas?

**Comment by tombruijn** [comment]
Hi @KateWilkins !

The backup gem really isn't meant to work alongside Rails in the same project. We recommend you extract the backup gem config into its own project.

Is what I usually say, but it also looks like that you're also not using bundler to manage backup's dependencies. Can you try setting it up with bundler in a separate project?

**Comment by KateWilkins** [comment]
Hi Tom,
I've now made a simple Gemfile with just backup in it and done a bundle install and its working ok, thanks.

Might be worth a note in the docs as the bundle method isn't covered.

**Comment by tombruijn** [comment]
Hi @KateWilkins,

good to hear it's working now. We already cover some use cases of bundler in the documentation, http://backup.github.io/backup/v4/installation/, but we also don't want to force people to use it. Everyone has their own environment and setup
