### ISSUE TITLE
Is this possible to not store gzipped tar inside another tar?

### ISSUE THREAD

**Issue by imcookie** [backup/backup#798]
I mean my backup file look's like .tar and inside this file i have tar.gz.  How to disable this feature?

**Comment by tombruijn** [comment]
This is the backup archiving setup. It creates archives for all the separate things you've configured in your model and then combines them all in one package, the .tar, for easy transferring of the backup file

**Comment by franciscopaniskaseker** [comment]
Reopen. The problem to create another tar is use double of space to create backup. If, for example, I have only one big file I will need the double space size to tar after compress that backup. It is not efficient... So what can I do?

**Comment by tombruijn** [comment]
> So what can I do?

Nothing unfortunately. The problem you're describing is known and not easy to fix. It's a core part of how the backup pipeline works right now. In order to not store intermediate steps on disk we'd need to rewrite the entire pipeline, which is no easy task.
