### ISSUE TITLE
Possible to support encryption on a per storage location basis?

### ISSUE THREAD

**Issue by styro** [backup/backup#800]
I don't see a way to do this without reworking everything, but would it be possible to allow encryption to be enabled on only some storage and/or sync definitions?

eg I'd like to have a rotation of local unencrypted backups for quick restores and/or test db refreshes, but only send encrypted backups offsite (eg to S3).

**Comment by tombruijn** [comment]
Unfortunately that wouldn't be possible with the current backup pipeline. You would have to create separate backup models for it.
