### ISSUE TITLE
backup all databases for mongo

### ISSUE THREAD

**Issue by DoctorOgg** [backup/backup#802]
it does not appear the feature was ever added to backup all mongo databases, any idea if this was added, or will be added?

Thanks!

**Comment by DoctorOgg** [comment]
im guessing this project is not actively maintained?

**Comment by tombruijn** [comment]
If mongodump supports it backup should too. Otherwise you could always query the DB in advance, get a list of all databases and dynamically create configuration for every database.

Please see #803 for more information on the status or why it may take a while to get a response.
