### ISSUE TITLE
gpg invocation not working

### ISSUE THREAD

**Issue by jjb** [backup/backup#804]
for some reason the gpg invocation suggested here: http://backup.github.io/backup/v4/encryptor-gpg/#decrypting

doesn't work:

```
$ gpg -d github.tar.gpg -o github.tar
usage: gpg [options] --decrypt [filename]
```

even though the manpage for my gpg version does say that the `-o` flag can be used for specifying the output file. 

This is successful:

```
gpg -d github.tar.gpg > github.tar
```

**Comment by stuartellis** [comment]
Hello John,

Could you specify the OS and GPG versions that you used to encrypt and decrypt?

**Comment by jjb** [comment]
Ubuntu 14.04.5

gpg 1.4.16

**Comment by stuartellis** [comment]
Thank you for that.

It seems that the order of the flags is significant, at least on that version of GPG. This should work:

gpg -o github.tar -d github.tar.gpg

I'll investigate a bit further, and put in an update to the documentation.

**Comment by stuartellis** [comment]
I've amended the documentation. Better late than never, I suppose.
