### ISSUE TITLE
Use a Ruby style guide

### ISSUE THREAD

**Issue by tombruijn** [backup/backup#805]
Use Rubocop for style guide control.

I still have the config from my last (proprietary) project that we can use as a basis.

Rubocop also offers an auto-fix for existing code and can generate a TODO set of rules that will still have to be fixed afterward.

**Comment by stuartellis** [comment]
OK. I haven't used Rubocop, so a working config would be great.

If this is in line with your preferred style, I can add it to CONTRIBUTING.md:

https://github.com/bbatsov/ruby-style-guide
