### ISSUE TITLE
Create a guide for contributors

### ISSUE THREAD

**Issue by stuartellis** [backup/backup#806]
Create a document for setting up the project for development.

We could use the text of the Contributing page for AppSignal as a basis:

https://github.com/appsignal/appsignal-docs/pull/48

**Comment by tombruijn** [comment]
I made a careful start at AppSignal writing a contributor guide you linked. It's a high level description of how to contribute to basically any kind of (open source) project. We should, along with #808, describe how to report an issue, what kind of information we need, how to submit a PR and what standards it needs to follow.

**Comment by stuartellis** [comment]
#809 has a first pass at implementing a CONTRIBUTING.md, loosely based on your AppSignal guide, and the one for factory_girl_rails, which : https://raw.githubusercontent.com/thoughtbot/factory_girl_rails/master/CONTRIBUTING.md. I also looked at the CONTRIBUTING file for Rust: https://raw.githubusercontent.com/rust-lang/rust/master/CONTRIBUTING.md

**Comment by stuartellis** [comment]
I've now merged PR #809, which provides a CONTRIBUTING.md, and have opened #812 to specifically track work on a longer DEVELOPING.md document.
