### ISSUE TITLE
Replace Vagrant test environment with Docker

### ISSUE THREAD

**Issue by stuartellis** [backup/backup#807]
The Vagrant test environment currently has issues, and is configured to use a base box that is not publicly available (see issue #546). One option is to replace it with an environment defined by Docker Compose.

**Comment by tombruijn** [comment]
We should definitely try to get this working again. I don't think we need any particular set of features from vagrant. Docker with docker compose will do fine.

We can add tests for local databases, remote databases, remote and third party services like AWS S3 and others. Let's make a list of tests we need before we start implementing it.

- [ ] Full integration test of the gem
- [ ] AWS S3
- [ ] Docker
- [ ] Local databases
- [ ] Remote databases
- [ ] Various notifiers
- etc

**Comment by stuartellis** [comment]
I really like how Ansible handle support for the half-a-zillion modules that they ship: modules are marked as either "core" or "extra" ([documentation](http://docs.ansible.com/ansible/modules.html)). If you are happy to split the plugins up like this, we could focus on a test setup that supports the "core" plugins for the first version.

FWIW, since I needed a clean environment, I created a basic Docker config, which is in a [branch in my fork](https://github.com/stuartellis/backup/tree/feature/docker).

**Comment by tombruijn** [comment]
Your docker setup looks ok. Not sold on the rbenv setup to install Ruby. We could also use one of the Ruby images as a base image https://hub.docker.com/_/ruby/
Same for other tools and services we want to test.

We'll probably need a few images to set up different situations and make a small script around it to automate all the tests. 

We can even hook it up in the CI. Travis should have support for docker https://docs.travis-ci.com/user/docker/

**Comment by stuartellis** [comment]
I think that developing something for Travis to run is a really good idea. We could do various things with Docker, but if we aim for making it run on Travis then that provides a guide.

Looking at the `vagrant/spec/` directory, the current tests cover:

**Databases** 

- [ ] MongoDB
- [ ] MySQL
- [ ] PostgreSQL
- [ ] Redis
- [ ] Riak

**Encryptors**

- [ ]  GnuPG

**Storage**

- [ ] FTP
- [ ] Local Filesystem
- [ ] `rsync`
- [ ] `scp`
- [ ] `sftp`

**Syncers**

- [ ] `rsync`

**Comment by tombruijn** [comment]
For the remote services it's probably best to set up test accounts, and have proper cleanup in place so we don't pay for test artifacts being left behind taking up space.

If we mock the endpoints we don't test anything more than the unit tests do.

It's probably best to leave these remote services for last and focus on non-third-party tools first. I'm sure there are also other databases en storage types that could use integration tests.

**Comment by stuartellis** [comment]
An update: After being buried by other stuff, I've actually had some free time again and got the RSpec tests running on Travis with Docker (stuartellis/backup fork, branch feature/docker-testing). The Docker image could provide a development environment, since it shares the repo directory with the host system, but I haven't explored that beyond adding Rake tasks to build an image and run a bash shell inside a container.

The next step is adapting the Vagrant tests to run inside the container.

**Comment by tombruijn** [comment]
Yeah same about being buried under other stuff.. :|

Changes so far look good. We can recommend the docker container for development and running unit tests.

> The Docker image could provide a development environment, since it shares the repo directory with the host system, but I haven't explored that beyond adding Rake tasks to build an image and run a bash shell inside a container.

Not sure what mean here. If you need help with setting up a docker I can help. I have done more docker in the past few months than a sane person probably should..

**Comment by stuartellis** [comment]
> Not sure what mean here.

I'd like bin/backup etc. to run from the shell inside Docker, so that you can edit the source and re-run the tools inside the container. I've just pushed a change to the feature/docker-testing branch that sets the RUBYPATH for containers launched by Rake tasks, so things work if Ruby is run with the -S option:

`ruby -Ilib -S bin/backup version`

**Comment by stuartellis** [comment]
I have updated the feature/docker-testing branch: it now runs the acceptance tests that work with local files.

**Comment by tombruijn** [comment]
@stuartellis awesome!

Could you perhaps already create a PR so I can more easily follow the progress? (I don't get notifications for commits referencing an issue.) And give some feedback if needed.

**Comment by stuartellis** [comment]
OK, I've now opened PR #832 for this.
