### ISSUE TITLE
Add a DEVELOPING.md file to document the development process

### ISSUE THREAD

**Issue by stuartellis** [backup/backup#812]
GitHub automatically shows the contents of CONTRIBUTING.md to both bug reporters and potential contributors, so we should have a separate document to explain the development workflow.

Possible items to cover:

* Setting up a development environment
* Coding style (see #805)
* Branching and git workflow for this project
* How to test changes locally

**Comment by tombruijn** [comment]
Got my vote :)

We might need to go in depth in how to set up a Ruby environment and such or maybe recommend a docker container for development purposes (although that means setting up docker, replacing one setup with another). The "problem" is that there are also quite a few non-ruby developers using backup as their backup tool, and a guide to help them setup a dev environment would be very helpful.

I'm working on #805 in #814 

The git branching process is quite simple right now. We merge everything on master and use feature branches and PRs to merge changes. But we might want to follow semver better than we do now by incorporating it in our branch setup. and use `master` for patch releases and `develop` for minor/major releases.

**Comment by stuartellis** [comment]
I'm currently thinking that I'd like to get something in place for #807, and then come back to this. 

If you don't already know Ruby then setting up a Ruby development environment is probably challenging, since the tools are scattered (chruby/rbenv/rvm, Bundler, RubyGems, plus native dependencies). Once we use containers for testing, then I'd be interested in seeing if we can get a usable (and probably optional) container-ized development environment.

**Comment by tombruijn** [comment]
> I'm currently thinking that I'd like to get something in place for #807

Okay 👍
