### ISSUE TITLE
keep not deleting old local files.

### ISSUE THREAD

**Issue by max-allan-surevine** [backup/backup#815]
I'm having some trouble with keep not removing old local files. My config etc. is attached.
In summary, it works fine with S3 storage and Rackspace but the local files keep building up!
I have 25 local daily files instead of 7 and (as expected) 5 daily files in S3 and 14 files in Rackspace.

I am using a variable $keep set from config.rb to set the keep value differently for daily/weekly/monthly. That is working fine for S3. But, even if I override the variable and set "local.keep=5" I have lots of local files that never get deleted.

1. gem install backup --version 4.3.0
2. backup check
3. backup perform  -t daily_backup
Config and model files attached.
Running:
* Operating system: AWS Linux
* Ruby version:  2.0.0p648
[model.txt](https://github.com/backup/backup/files/606357/model.txt)
[config.txt](https://github.com/backup/backup/files/606358/config.txt)

**Comment by max-allan-surevine** [comment]
My Local-daily.yml file is getting truncated to only 2 backups, but the files are not being removed from the disk :
```
[root@jira daily_backup]# more Local-daily.yml 
---
- !ruby/object:Backup::Package
  trigger: daily_backup
  extension: tar.gpg
  chunk_suffixes: []
  no_cycle: true
  version: 4.3.0
  time: 2016.11.22.14.56.48
- !ruby/object:Backup::Package
  trigger: daily_backup
  extension: tar.gpg
  chunk_suffixes: []
  no_cycle: true
  version: 4.3.0
  time: 2016.11.22.14.56.42
[root@jira daily_backup]# lsl -latr /var/localbackup/jira.test/daily/daily_backup
-bash: lsl: command not found
[root@jira daily_backup]# ls -latr /var/localbackup/jira.test/daily/daily_backup
total 32
drwxr-xr-x 2 root root 4096 Nov 22 14:30 2016.11.22.14.30.37
drwxr-xr-x 3 root root 4096 Nov 22 14:30 ..
drwxr-xr-x 2 root root 4096 Nov 22 14:31 2016.11.22.14.31.21
drwxr-xr-x 2 root root 4096 Nov 22 14:31 2016.11.22.14.31.34
drwxr-xr-x 2 root root 4096 Nov 22 14:45 2016.11.22.14.45.34
drwxr-xr-x 2 root root 4096 Nov 22 14:56 2016.11.22.14.56.42
drwxr-xr-x 2 root root 4096 Nov 22 14:56 2016.11.22.14.56.48
```

**Comment by max-allan-surevine** [comment]
OK, so this looks like because I'm using CloudFiles AND Local , no_cycle is being set to true for the Local backup. Instead of pushing it to a CF_daily.yml file. 
(which would probably avoid the need for the no_cycle value being set anyway, use the logic that if you're looking at cycling for the CF module, then just don't do it.)
In fact, even if I name my CloudFiles :
`  store_with CloudFiles, :rack do |cf|`
Then it still makes the Local_daily.yml have a no_cycle. Shouldn't that at least go into a Local_rack.yml ?? 

The oddest thing is that S3_daily.yml gets it right. Maybe there is a failure to initialise no_cycle when creating the Local_daily file.. ?

**Comment by max-allan-surevine** [comment]
I added a no.cycle=false to backup-4.3.0/lib/backup/storage/local.rb
```
          FileUtils.send(transfer_method, src, dest)
        end
        package.no_cycle=false
      end
```
No idea if that's "safe" but it seems to be cycling properly now. Would someone with more knowledge like to consider that fix and apply it if it's good?

**Comment by max-allan-surevine** [comment]
NB this still happens on 5.0.0. beta 2. My previous fix still seems valid.

**Comment by jstdoit** [comment]
this error still happens, old backups not deleted.

**Comment by max-allan-surevine** [comment]
Still needs someone to consider my suggestion and merge it in.

**Comment by max-allan-surevine** [comment]
Still needs someone to consider my suggestion and merge it in.
