### ISSUE TITLE
Periodic Github Commits

### ISSUE THREAD

**Issue by sinanerdem** [backup/backup#828]
In order to backup our code on Github (or even Bitbucket) we normally use periodic scripts to commit. Is it a feasible function to expect from this project? Is there any existing method for this?

**Comment by tombruijn** [comment]
You want to backup GitHub repos?
That's not supported by backup currently.

You could leverage a before hook (http://backup.github.io/backup/v4/before-after-hooks/) save the repo to a directory and/or pull new changes in a local clone, then use the archiver http://backup.github.io/backup/v4/archives/ to backup a certain directory.

Would that work?

**Comment by shakycode** [comment]
@sinanerdem So your use case is committing code to github/bitbucket but you also want a copy of it via the backup gem?  I get the idea of redundancy, but this seems a bit complex and IMHO a bit overkill even using a before hook as @tombruijn suggested.

You can also setup backup to backup your deployed github directory on your app server which might be an easier "kill".

**Comment by stuartellis** [comment]
I'm closing this ticket, since the original question has been answered. @sinanerdem - if you have any other questions, please feel free to open another ticket, or visit the #backup Gitter channel.
