### ISSUE TITLE
pipeline: make packager optional?

### ISSUE THREAD

**Issue by piitaj** [backup/backup#831]
Hi!

I am opening a ticket which was already discussed in :"tar.gz in a tar file #718". 
The reason I am opening is, that we back up large quantities of data with this wonderful script, but every backup needs twice the amount of space to back up as the original file-set. 

I took a quick peek into the source code and found ,that this is because of how the archiver-packager pipeline is designed, more specifically: 
-we create the archives and add compression if requested
-after the archives are made, we "package" the whole thing which is a nice feature for portability as noted, also we can request the encryption and splitting to happen if needed

Our idea is that if we make the packager optional, (lets say we don't need encryption and splitting in our model) than we could save a lot of temporary disk backup space for the process. (also it would save some time as well). 

I am guessing that this wouldn't be such a big task to implement, but please correct me if I am wrong.  We were thinking of trying to implement it ourselves in a way, like we could add a "packager none" type of option to the model, which would then bypass the whole packaging part.

Please let me know of your thoughts on the subject.

Best regards

**Comment by stuartellis** [comment]
@piitaj - if you are definitely interested in working on this, please do join the #backup-dev channel on Gitter and we can progress it. Fixing the pipeline has been discussed, but unfortunately it won't happen without some motivated to do the work.
