### ISSUE TITLE
Backups fails sometimes with @^

### ISSUE THREAD

**Issue by borriglione** [backup/backup#833]
## What went wrong?

We have a nodejs application with a PostgreSQL database which is "backuped" every day. In ~6 of 7 cases it works well but sometimes the backup fails and seems to crash the whole server. We have to manually restart the server in this case.

The server crash happens 1-2min after the backup started. The server never hang of when the backup is disabled.

The log file looks like:

```
[2016/12/09 07:10:56][info] Packaging the backup files...
[2016/12/09 07:10:56][info] Using Encryptor::OpenSSL to encrypt the archive.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
```

We thought the error comes from the OpenSSL encryption and disabled it but then the error occurred like:

```
[2017/01/14 09:09:06][info] Archive 'shared' Complete!
[2017/01/14 09:09:06][info] Packaging the backup files...
[2017/01/14 09:09:07][info] Packaging Complete!
[2017/01/14 09:09:07][info] Cleaning up the temporary files...
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
```

In the var/log/syslog I only find this strange errors ^@^@^..... too as last entry before the server freezed. 

## What steps did you follow?

The backup is running by crontab

```
8 10 * * * /bin/bash -lc 'backup perform -t deploy'
```

## How is your copy of backup configured?

config.rb
```
  Storage::FTP.defaults do |server|
    server.username     = "xxx"
    server.password     = "aaa"
    server.ip           = "abc.de"
    server.port         = 21
    server.path         = "~/backup/"
    server.keep         = 1
    server.passive_mode = false
  end
```

our deploy model
```
Model.new(:deploy, 'Backing up deploy user') do
  compress_with Gzip

  archive :shared do |archive|
    archive.add "/home/deploy/production/shared"
    archive.exclude "/home/deploy/production/shared/tmp/"
  end

  store_with FTP do |server|
    server.path         = "~/deploy/"
    server.keep         = 10
  end

  database PostgreSQL do |db|
    db.name               = "db_name"
    db.username           = "db_user"
    db.password           = "db_pass"
    db.host               = "localhost"
    db.port               = 5432
  end

  encrypt_with OpenSSL do |encryption|
    encryption.password = 'placeholder'
    encryption.base64   = true
    encryption.salt     = true
  end
end
```

## System

* Backup 4.2.2
* Ubuntu 14.04.5 LTS
* ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
* Postgres 9.3

**Comment by stuartellis** [comment]
@borriglione: I'd like to resolve this, if we can. The current release is 4.4.0 and we also have an RC of Backup 5.0.0. Please can you let us know if this is still an issue for you with the current version?

**Comment by borriglione** [comment]
I never found out if its really a Backup-issue or a server / hard-drive crash.
We finally kicked the old server and moved to a new one. As the problem never occurred there again this issue can be closed.

Anyway thanks @stuartellis for your comment
