### ISSUE TITLE
When perform backup, the log won't print immediately

### ISSUE THREAD

**Issue by bastengao** [backup/backup#834]
##  When perform backup, the log won't print immediately

I have a very large database on mongodb about 10 GB. When I perform backup, it takes a long time and the log doesn't print immediately. I cant see any thing before the process finished.

I see `run` utilities method uses `Open4. popen4`. Here  https://github.com/backup/backup/blob/master/lib/backup/utilities.rb#L175 . May be this is the issue.

* Operating system: Ubuntu Server 14.04.5
* Ruby version: 2.2.3
* Tools or services used by backup: mongodump

**Comment by tombruijn** [comment]
Correct. Backup only prints when a command has completed. We can't really change that right now.  Sorry about that
