### ISSUE TITLE
Issue with MySQL backup hanging (innobackupex)

### ISSUE THREAD

**Issue by alecgo** [backup/backup#839]
## What went wrong?

`innobackupex` seems to hang at job started.  No further diskspace is being used, no CPU usage on the box at all.  No `innobackupex` process is running.

## What steps did you follow?

Ran a task to backup all mysql databases.

1. gem install backup --version 4.4.0
2. backup check
3. backup perform -t cc14

Output:
```
[2017/02/21 16:00:41][info] Performing Backup for 'Perform backups of MySQL Databases (cc14)'!
[2017/02/21 16:00:41][info] [ backup 4.4.0 : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux] ]
[2017/02/21 16:00:41][info] Database::MySQL Started...
```

## How is your copy of backup configured?

empty config.rb

models/cc14.rb
```
Model.new("cc14", 'Perform backups of MySQL Databases') do

  database MySQL do |db|
    db.name   = :all
    db.socket = "/var/run/mysqld/mysqld.sock"
    db.host   = "localhost"
    db.port   = 3306

    db.backup_engine = :innobackupex
    db.sudo_user = "root"

    db.username           = "backup"
    db.password           = "PASSWORD"

    db.verbose = true
    db.prepare_options = ["--use-memory=768M"]
  end

  store_with S3 do |s3|
    s3.use_iam_profile = true
    s3.region            = "us-east-1"
    s3.bucket            = "my-backup"
  end
end
```

## Tell us about the computer that runs the backup gem

* Operating system: Ubuntu Server 14.04.5
* Ruby version: 2.3.3
* MySql: 5.6.35-80
* innobackupex: 2.3.6

**Comment by stuartellis** [comment]
Hello Alec,

Can you try manually running the innobackupex command-line tool on the same computer in the same user account that Backup uses?

**Comment by stuartellis** [comment]
OK, I'm not sure: I would actually be tempted to either use a debugger or just add some puts() statements in the innobackupex() of lib/database/mysql.rb to double-check what command-line statement Backup is actually constructing.

The only other thing I notice that you are using the /usr/local/ directory?

**Comment by alecgoebel** [comment]
Yes, but all the commands know to use that. Also the innobackupex commands
generated seem to run fine. I wound up just doing a bash script doing the
same thing since I ran out of time on this project.

**Comment by stuartellis** [comment]
I'm closing this ticket, because I don't think that we have enough information to progress it.

@alecgo - If you want to pick this up again, please feel free to re-open the ticket.
