### ISSUE TITLE
Dependency json 1.8.2 is not compatible with Ruby 2.4.1 

### ISSUE THREAD

**Issue by lucianghinda** [backup/backup#855]
## What went wrong?

While trying to install backup with Ruby 2.4.1 I get the same error because of dependency of json 1.8.2 as the one described here: https://github.com/rails/rails/issues/27450

## What steps did you follow?

1. Install Ruby version 2.4.1
2. gem install backup

## Tell us about the computer that runs the backup gem

* Operating system: Ubuntu 14.04.4 LTS
* Ruby version: 2.4.1

**Comment by tombruijn** [comment]
Thanks for the report!
We don't support Ruby 2.4 in the currently released version 4 series though. I've added support in #830 which is scheduled to be released in v5.

**Comment by ConfusedVorlon** [comment]
an observation here: Version 5.0 is removing a lot of functionality. The part that I care about is s3 syncing. 

I use 2.4 though, so can't use v4.

**Comment by tombruijn** [comment]
Hi @ConfusedVorlon, v5 doesn't remove functionality, it deprecates it. (But honestly I don't think that will happen in a full release.) You should be able to use the v5 beta with Ruby 2.4

**Comment by ConfusedVorlon** [comment]
thanks for the clarification. I do hope you at least keep s3 functionality in the end...
