### ISSUE TITLE
GnuGPG Path Option?

### ISSUE THREAD

**Issue by br00tal** [backup/backup#858]
## What went wrong?

My distribution (Arch) only ships GnuGPG 2.x, which doesn't appear to be supported by backup.

**Please give us a brief description of the problem, including the text of any error messages**

The encryption phase of the backup process fails with a gpg non-zero exit code.  This is likely because it's GnuGPG 2.x.

Is there an option to override the path to gpg, or something similar?  I was going to build GnuGPG 1.4 and install it in a different location, and have backup use that binary instead.

Any ideas would be helpful, thanks.

**Comment by tombruijn** [comment]
Hi @br00tal 

this should be configurable through the utilities configuration. See the docs: http://backup.github.io/backup/v4/utilities/

**Comment by br00tal** [comment]
I can't believe I missed that in the documentation.  That's exactly what I'm looking for, thanks!
