### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by SimonMiaou** [backup/backup#859]
Following the issue about ruby 2.4 compatibility (#855)

I know that you don't want to promise support for 2.4 until version 5 of the gem.
But as the repository is active and there is regular improvements, would it be possible to release new versions more often so we could benefit the recent changes?

**Comment by tombruijn** [comment]
I've just pushed the last deprecation on #853, so we should be good to release a new version when that's merged.

about shipping more versions more often. Probably not, we're looking into what we want to do with the project. Just merging in new features and support is going make this unmaintainable.

**Comment by SimonMiaou** [comment]
Thanks for the information. I understand your point of view about shipping more often but I think shipping more doesn't mean changing the way you work. However I will not push for it.

Looking forward the next version 😄

**Comment by tombruijn** [comment]
Version 5.0.0.beta.1 has been released 🎉 
Try it out and let me know if it works! https://rubygems.org/gems/backup/versions/5.0.0.beta.1

**Comment by SimonMiaou** [comment]
Coming back here after a while.
Sorry I didn't confirm before but it works like a charm since then.
Thank you !
