### ISSUE TITLE
ca-central-1 region supported?

### ISSUE THREAD

**Issue by nozpheratu** [backup/backup#860]
## What went wrong?

Tried to use the S3 storage provider with the region set to the new ca-central-1 AWS region.

Backup storage fails with the error code "IncompleteBody" and message "The request body terminated unexpectedly".

## How is your copy of backup configured?
```ruby
store_with S3 do |s3|
  s3.region            = "ca-central-1"
  s3.access_key_id     = "..."
  s3.secret_access_key = "..."
  s3.bucket            = "my-bucket"
end
```

config.rb file is set to all defaults.

## Tell us about the computer that runs the backup gem

**Change the information below to match the details of your computer**

* Operating system: Ubuntu Server 16.04
* Ruby version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
* Tools or services used by backup: Postgres 5

**Comment by stuartellis** [comment]
Hello @nozpheratu - is it possible for you to test with Backup version 5.0.0.beta.1, and let us know if this is still an issue with the new version?

**Comment by nozpheratu** [comment]
@stuartellis It's giving me an invalid header value now.

**Comment by nozpheratu** [comment]
@stuartellis Same problem sadly.

**Comment by nozpheratu** [comment]
I think ca-central-1 wasn't supported by fog until v1.3. I'm going to experiment locally with an updated fog and see if it fixes this.

**Comment by nozpheratu** [comment]
I tried updating fog to 1.4 and I'm still getting the same error sadly.

**Comment by nozpheratu** [comment]
Seems setting `s3.fog_options = { endpoint: "https://s3.ca-central-1.amazonaws.com" }` helped.
