### ISSUE TITLE
Rails how to set to another dir?

### ISSUE THREAD

**Issue by dcalixto** [backup/backup#861]
After install and generate the Backup the Backup folder with the model, config, and logs goes to user home directory,

so, how to create the Backup to another dir? for exemple i would like to create to /data

no i mean
the entire backup folder
for exemple
if you genterate a backup
like this
backup generate:model --trigger=db_backup --databases='postgresql' --storages=‘dropbox’ --compressor='gzip' --notifiers='mail'
will generate a folder Backup with everything
the config file
the log folder
and where the backups stays
but generate at /home/ubuntu
i would like to generate on another dir

someone know how?

**Comment by tombruijn** [comment]
You can set the `root_path` in `config.rb` as described in the config.rb file: http://backup.github.io/backup/v4/generator/

**Comment by dcalixto** [comment]
issue solved


i had to use



```
export HOME=/data
backup generate:model --trigger=db_backup --databases='postgresql' --storages=‘dropbox’ --compressor='gzip' --notifiers='mail'
export HOME=/home/ubuntu
```
