### ISSUE TITLE
How to automate this dropbox session?

### ISSUE THREAD

**Issue by dcalixto** [backup/backup#865]
The gem is working greatly but everytime to backup to dropbox show this, how to authorize automatically? 

[2017/05/16 23:30:03][info] Creating a new session!

Visit the following URL to authorize your Dropbox App with Backup:

  https://www.dropbox.com/1/oauth/authorize?oauth_token=cA1yRPcurFfnRnMq

Hit "Enter/Return" once you're authorized.

**Comment by pawlik** [comment]
Maybe it can't access cache file (https://github.com/backup/backup/blob/master/lib/backup/storage/dropbox.rb#L155) check if you have r/w rights, and execution right in the parent folder to create `.cache`. 
But check user permissions which is performing the backup.

In my case the path is `~/Backup/.cache/` (I didn't find any info if it's configurable or not) and inside there's a file which name is something resembling hash, and inside few entries like
```
- hash
- another_hash
- yet_another_hash
```

**Comment by dcalixto** [comment]
thank you @pawlik , so this is due the cache? ok!
well, every time that cron start the backup dropbox asks for the auth with different oauth_token. 
so this is related to cache?

**Comment by stuartellis** [comment]
@dcalixto - Please note that Dropbox is dropping support for the Ruby gem and the API that it uses next month (issue #838).

**Comment by pawlik** [comment]
@dcalixto I'm not 100% sure, but I would say this is the first place you should check.
