### ISSUE TITLE
Snapshotting with hard links?

### ISSUE THREAD

**Issue by neidiom** [backup/backup#869]
I would like to backup a large folder via rsync to a local storage and keep 7 daily copes. I am using rsnapshot for this which uses hard links which saves allot of disk space. It something like this possible with the backup gem?

**Comment by tomlobato** [comment]
Not builtin, but I`ve faced the same challenge and found that the best approach is to keep backup only syncing the files and leave with rsnaphot the task of data rotation.
So far this approach is working great for me.

```/backup/system/rsnaphot.conf```:

```

# conf geral
config_version	1.2
verbose			2
loglevel		3
cmd_rm			/bin/rm
cmd_rsync		/usr/bin/rsync
cmd_logger		/usr/bin/logger

# intervals
interval	hourly	48
interval	daily	60
interval	monthly	12

# Custom
snapshot_root	/backup/timemachine
cmd_cp		/bin/cp
lockfile	/var/run/rsnapshot-timemachine.pid

# backups
backup_exec	/root/.rbenv/shims/backup perform -t my_backup -c /backup/system/ruby-backup/config.rb		required

```

Then, ```/etc/crontab```:

```
30 *      * * *     root  /backup/system/backup.sh hourly
0 1       * * *     root  /backup/system/backup.sh daily
0 3       1 * *     root  /backup/system/backup.sh monthly
```

Just make sure to set your backup path to 
```/backup/timemachine/hourly.0/``` or some subfolder of it in ```models/*bk models*```, like:

```ruby
 sync_with RSync::Pull do |r|
     r.path = "/backup/timemachine/hourly.0/server1"
    ...
```

**Comment by stuartellis** [comment]
Personally, I would look at [Duplicity](http://duplicity.nongnu.org/) or the newer [https://restic.github.io/](Restic) for this sort of thing. IMO, the strengths of Backup are elsewhere (support for databases, notifiers etc.).
