### ISSUE TITLE
S3 syncer with infrequent access storage class

### ISSUE THREAD

**Issue by ukasiu** [backup/backup#870]
Is there any specific reason for no :standard_ia in [lib/backup/syncer/cloud/s3.rb](https://github.com/backup/backup/blob/037214cdbb7f83bf6ce471d92a9b4f8260d53d31/lib/backup/syncer/cloud/s3.rb)

**Comment by stuartellis** [comment]
I don't think so - it just hasn't been implemented :)

It is a good idea, though.
