### ISSUE TITLE
Disable tar procedure after the backup is executed

### ISSUE THREAD

**Issue by lzecca78** [backup/backup#872]
Backup version : 4.4.0

I am facing a weird issue on the backup: i am using mysql backup model with 1 database with local storage.
What i would like is really easy : avoid the tar archiving. 
I have deleted every block related to archive, but, no way, it keeps to tar it and move to the local path variable, instead of moving  bzipped dump without doing anything. 
This is a nonsense feature because i need to extract an already compressed bz2 dump that is even nested in a directory hierarchy. 
Is there any way to avoid this redundant and useless tar task?

**Comment by stuartellis** [comment]
Per Gitter conversation, the output format isn't really adjustable (unfortunately).
