### ISSUE TITLE
Update supported Ruby versions

### ISSUE THREAD

**Issue by oogali** [backup/backup#873]
## What went wrong?

The installation documentation says that Ruby 2.0, 2.1, and 2.2 are supported.

However, the Travis CI configuration is [successfully] testing against Ruby 2.1, 2.2, 2.3, and 2.4.

The documentation should be updated to reflect that backup **is** functional on Ruby 2.3 and 2.4, and either Ruby 2.0 is removed from the documentation or Ruby 2.0 is added to the Travis CI configuration. 

## What steps did you follow?

This was after a quick review of the Travis CI configuration.

## How is your copy of backup configured?

Not applicable here.

## Tell us about the computer that runs the backup gem

Not really applicable here as well, but Travis CI.

**Comment by tombruijn** [comment]
hi @oogali! Good catch!
You're free to update the documentation. The code for the http://backup.github.io/backup website can be found on the `gh-pages` branch of this repo. Once you push your changes they should automatically appear there :)
