### ISSUE TITLE
Create a test plan

### ISSUE THREAD

**Issue by stuartellis** [backup/backup#884]
In order to unblock version 5.0, we need to identify core functionality and create a reasonable test plan to validate these features.

This will require:

a) Identifying the features that can reasonably be considered "core". Other features are "extras".
b) Marking the status of features in code or documentation
c) For each core feature, identifying a test. This may be a unit test, an integration test, or a manual test.
d) Defining one or more test environments to carry out the tests. Travis CI will execute unit and integration tests. PR #857 provides a Docker environment that may be useful for manual testing. The test environments will need to include one or more specific Ruby versions, resolving ticket #873.

**Comment by stuartellis** [comment]
I have now pushed changes to the documentation Website to mark features as Core or Extra.

**Comment by stuartellis** [comment]
Functionality to test:

**Databases** 
- [ ] MongoDB
- [ ] MySQL
- [ ] PostgreSQL
- [ ] Redis
- [ ] SQLite

**Compressors**
- []  GZip

**Encryptors**
- []  GnuPG
- []  OpenSSL

**Notifiers**
- [ ] Email
- [ ] HTTP
- [ ] AWS SES
- [ ] Slack

**Storage**
- [ ] AWS S3
- [ ] Local Filesystem
- [ ] `rsync`
- [ ] `scp`
- [ ] `sftp`

**Syncers**
- [ ] AWS S3
- [ ] `rsync`

**Comment by lostapathy** [comment]
A few thoughts to ease this progress (not sure if now or more for if this project makes it to 6.0)

Have you thought about spinning out the non-core backends into separate gems?  That would allow delegating the maintenance out for those backends, and also allow you to update and ship the core even if some of the "extra" backends weren't ready yet.  And if nobody steps up to help fix them, it's easier to just let them go.

Would also help reduce the amount of deps required in the gemfile for a more "basic" user.

If that's a strategy you're interested in I could probably help work on it.

**Comment by stuartellis** [comment]
Hello @lostapathy - I think that would be a good idea, but would require more active maintainers than we currently have. If you are interested in moving this project forward then we would certainly welcome the help: feel free to drop to our _backup-dev_ Gitter channel.
