### ISSUE TITLE
CURL command notifier (23) Failed writing body

### ISSUE THREAD

**Issue by arefaslani** [backup/backup#885]
I backup my postgres database using backup gem. I've set a command notifier to notify me through telegram messenger. This is the script that calls telegram api with CURL:
```bash
#!/bin/sh

/usr/bin/curl \
        -X POST \
        -d "{\"text\": \"$1\", \"chat_id\": \"[TELEGRAM_BOT_CHAT_ID]\"}" \
        -H "Content-Type: application/json" \ https://api.telegram.org/bot359959396:[TELEGRAM_BOT_IDENTIFIER]/sendMessage
```
and this is the backup gem configuration:

```ruby

# encoding: utf-8
Model.new(:influencer_marketing_db_backup, 'Description for influencer_marketing_db_backup') do
  database PostgreSQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name               = "influencer2_production"
    db.username           = "influencer2"
    db.password           = ENV['INFLUENCER2_DATABASE_PASSWORD']
    db.host               = "localhost"
    db.port               = 5432
    db.skip_tables        = []
    db.additional_options = ["-xc", "-E=utf8"]
  end

  store_with Dropbox do |db|
    db.api_key     = ENV['INFLUENCER2_DROPBOX_KEY']
    db.api_secret  = ENV['INFLUENCER2_DROPBOX_SECRET']
    db.cache_path  = ".cache"
    db.access_type = :app_folder
    db.path        = "/"
    db.keep        = 10
  end

  compress_with Gzip

  notify_by Command do |cmd|
    cmd.on_success = true
    cmd.on_warning = true
    cmd.on_failure = true

    cmd.command = '/usr/local/bin/notifytelegram'
    cmd.args = ["Backup %V"]
  end
end
```

when I run the backup command `backup perform --trigger influencer_marketing_db_backup` I get a CURL error:

`(23) Failed writing body`

How can I fix this issue?

**Comment by stuartellis** [comment]
Hello @arefaslani,

Thank you for a very clear report!

I think that the first thing to do is to check that the Curl command works when you run it manually.

**Comment by arefaslani** [comment]
Thanks @stuartellis 
CURL command works and prints the json response:
```json
{"ok":true,"result":{"message_id":248,"from":{"id":"[TELEGRAM_USER_ID]","first_name":"[TELEGRAM_BOT_NAME]","username":"[TELEGRAM_BOT_NAME]"},"chat":{"id": "[TELEGRAM_CHAT_ID]","title":"Pinto Monitoring","type":"group","all_members_are_administrators":true},"date":1503118443,"text":"hello world"}}%
```
But in the Backup gem notifier, it print an error:

`(23) Failed writing body`

**Comment by stuartellis** [comment]
@arefaslani - OK, does the _notifytelegram_ script work correctly if you run it manually? If not, try removing the line wrap characters (the _\_ character), so that the whole command is on one line.

**Comment by NARKOZ** [comment]
I also have the same problem. @arefaslani did you manage to solve it?

**Comment by arefaslani** [comment]
@stuartellis @NARKOZ Sorry for super late response. Unfortunately after dropbox support was dropped, I didn't looked for solving this problem, because I don't this awesome gem anymore...
