### ISSUE TITLE
allow to load config file from gems

### ISSUE THREAD

**Issue by patleb** [backup/backup#891]
Just wondering if you would be interested into adding this functionality to backup? I have an implementation [here](https://github.com/patleb/backup/commit/32568cf4fc1c30a86c68a013b4af7ad27e499a22).

**Comment by stuartellis** [comment]
Hello @patleb!

Is this a feature that you would find useful, or just an idea (that was easy to prototype)?

**Comment by patleb** [comment]
I'm actually using it. It's very useful for sharing code between projects, it allows me to use the same configuration for a whole bunch of projects with minimal time when I want to update the way I backup similar projects. Although, there is a catch, you must use a separate Gemfile when you use `backup` and manage versioning by inspecting the project `Gemfile.lock`:

```ruby
# Backupfile

ruby_version = File.read('.ruby-version').strip
ruby ruby_version

gem 'backup'

gemfile_lock = File.read('Gemfile.lock').strip
version = /[\w\.]+/

any_gem_version = /^    any_gem \((#{version})\)$/
gem 'any_gem', gemfile_lock.match(any_gem_version)[1]

git_project_version = /^  revision: (\w+)\n  branch: \w+\n  specs:\n    git_project \(#{version}\)$/m
gem 'git_project', git: 'git@bitbucket.org:user_repo/git-project.git', ref: gemfile_lock.match(git_project_version)[1]
```

And, if you use capistrano, you will have to add a task to run `BUNDLE_GEMFILE=Backupfile bundle install`.
