### ISSUE TITLE
How do you run shell commands?

### ISSUE THREAD

**Issue by 2called-chaos** [backup/backup#895]
This might be a dump question but if I need to run a command to create a backup before doing something with it, would I just go about to use backticks or what is the recommended way?

Example:

```ruby
Model.new(:gitlab, 'Backup gitlab data') do
  before do
    `gitlab-rake gitlab:backup:create`
  end
  sync_with RSync::Push do |rsync|
    rsync.host     = "..."
    rsync.path     = "/opt/backups/butler/repositories"
    rsync.mirror   = true

    rsync.directories do |directory|
      directory.add "/var/opt/gitlab/backups"
    end
  end
end
```

**Comment by stuartellis** [comment]
There is no special syntax for this. You just need to think about how you are going to handle errors, e.g. https://stackoverflow.com/questions/4771930/catching-command-line-errors-using-x
