### ISSUE TITLE
Any plan for Google Cloud Platform support?

### ISSUE THREAD

**Issue by facundofarias** [backup/backup#897]
We are currently using the service that would be similar to s3 (GCP named the service as "Cloud Storage").

**Comment by tombruijn** [comment]
No, we don't have plans to support something new.
Backup is currently maintenance only, as is stated in the README.
We don't have time to work on the project and are looking for maintainers. If this sounds interesting to you, let us know in issue #803.

**Comment by lauramorillo** [comment]
@facundofarias I created last year this PR that maybe can help you to extend the library meanwhile: https://github.com/backup/backup/pull/827

I have not used it in some time, but maybe it still works and can help you with GCS!
