### ISSUE TITLE
Any plan for DigitalOcean Spaces support?

### ISSUE THREAD

**Issue by mitrm** [backup/backup#898]
https://developers.digitalocean.com/documentation/spaces/#introduction

**Comment by tombruijn** [comment]
No, we don't have plans to support something new.
Backup is currently maintenance only, as is stated in the README.
We don't have time to work on the project and are looking for maintainers. If this sounds interesting to you, let us know in issue #803.

**Comment by andrewsomething** [comment]
:wave: It's worth noting that DigitalOcean Spaces is S3 compatible. So you can actually use it with Backups already as you can pass configuration directly through to fog_options. Besides adjusting the endpoint, I've found that forcing usage of v2 signature type is also needed. Here's the config I'm using:


```ruby
  store_with S3 do |s3|
    s3.access_key_id     = "MYKEY"
    s3.secret_access_key = "MYSECRET"
    s3.region            = "nyc3"
    s3.bucket            = "log-space"
    s3.path              = "/"
    s3.keep              = 3
    s3.fog_options       = {
        :endpoint => 'https://nyc3.digitaloceanspaces.com",
        :aws_signature_version: 2
    }
  end
```

**Comment by nynhex** [comment]
Agreed, DO spaces works with the s3 adapter.  Plus I don't think we're actively adding new storage options.

**Comment by stuartellis** [comment]
@andrewsomething - Thanks for that.

I would be very happy to take a documentation patch to cover this: the docs Website is a standard Jekyll/GitHub Pages thing on the gh-pages branch.
