### ISSUE TITLE
MySQL timestamp

### ISSUE THREAD

**Issue by roberthallatt** [backup/backup#917]
## What went wrong?

Backup runs fine but the time stamp used for the mysqldump file outputs the time as UTC and does not reflect our local time zone. Is there anything that can be done to change this so that the time reflects your local time zone, perhaps introduce a new option in the config file?

* Operating system: CentOS release 6.9 (Final)
* ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
* Tools or services used by backup: Percona 5.5.55-38.8

**Comment by tombruijn** [comment]
Hi @roberthallatt ,

Backup uses the UTC time zone by default, not the time zone used by your machine. It's not possible to configure your preferred time zone.

I tend to point people to this comment: https://github.com/backup/backup/issues/641#issuecomment-85688354 when they do want a different time zone used for archive names.
With which you can override the Backup model's archive name (which is based on the time). If you want to modify the time zone used for the logger you'll probably have to override the method I point to in that comment.

Warning: use the modifications I linked to at your own risk ❗️
