### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by jimchild49** [backup/backup#935]
## when I try to install backup gem I get the following error (I use countries gem in my app)

```
fog-dnsimple's executable "console" conflicts with countries
Overwrite the executable? [yN]
```
I think it's find to answer the question here, but in multiple servers architecture I need to install the backup gem automatically after deploy

## What steps did you follow?

`gem install backup -v 5.0.0.beta.2`

**Comment by tombruijn** [comment]
Please use bundler for dependency management. Create a new Gemfile, add backup to it and run `bundle install`. Closing.
