### ISSUE TITLE
Is this being maintained? If so, please update the README

### ISSUE THREAD

**Issue by weedySeaDragon** [backup/backup#940]
### Is this project actively being maintained?  

I see this comment in https://github.com/backup/backup/issues/803#issuecomment-405803209  that says it _is_ being maintained and suggests that the README be updated,  and I see that PRs have been submitted and merged recently, but the README states that the project is in  maintenance mode.

I'd like to use this gem on a project I work on, but we're not clear about the status.  If the project is being maintained, can the README please be updated to reflect that?

**Comment by salsa-dev** [comment]
Hi, @weedySeaDragon !
Maintenance mode statement means exactly that the project is maintained but no further development planned. So, use this gem at your will, it has already been build quite solid.
