### ISSUE TITLE
Small doc grammer mistake

### ISSUE THREAD

**Issue by Roko131** [backup/backup#946]
https://backup.github.io/backup/v4/syncers/

Syncers are used to... depending on the Syncer and **it’s** configuration.

Should be:
Syncers are used to... depending on the Syncer and **its** configuration.

**Comment by elthariel** [comment]
Would you mind sending a PR for this ? :D

**Comment by Roko131** [comment]
First PR ever.

Hope it's good.

**Comment by elthariel** [comment]
It is :) Good job and thank you very much.

I hope this PR is the first one of a long series !

Welcome to the open source community !
