### ISSUE TITLE
Backup-ng has been forked! 

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [backup/backup#958]
Hello everyone,

backup was an excellent project, used by many sysadmins for backing up their servers. However, original maintainer abandoned it a long time ago, leaving it to its fate. An attempt to transfer project to new maintainers has been a failure so far. 

So, a new project backup-ng is forked and put on rails. I'm not ruby developer and I myself can contribute very little to code itself, at least for now, but I will gladly accept and merge your contributions. Backup-ng will continue where backup stopped, but it will eventually evolve to its own identity. 

Project can be found here:

https://github.com/backup-ng/backup-ng

All contributions are welcome, and i will gladly add more maintainers to the project.

**Comment by tombruijn** [comment]
It's been forked before. See also https://github.com/backup/backup/issues/803 if you want to contribute, maintain backup.
