### ISSUE TITLE
add variable date in file

### ISSUE THREAD

**Issue by tovoramaro** [backup/backup#963]
Hello,

I have a file "myfile_$(date +"_%y_%m_%d").gz" to save.
How can I insert this date variable in the "archive.add" part? 

Thank you,

Tovo.

**Comment by elthariel** [comment]
This is sort of a plain ruby question, not really specific to backup.

I'm not sure I completely understand your problem, but you should be able to do something with ruby string interpolation and the DateTime formatting methods
