### ISSUE TITLE
Error dumping tablespaces

### ISSUE THREAD

**Issue by danielristic** [backup/backup#969]
Hello,

My backups seem to work but the log show the following error:

`mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
`

I'm wondering it it actually impacts the dumps or it can be  ignored? (I'm using the default config for myslq).

* Operating system: Ubuntu Server 16.04.1
* Ruby version: 2.7.3
* Tools or services used by backup: MySQL 5.7.33

**Comment by elthariel** [comment]
I think it likely breaks the backup, according to a very quick google research. What's inside the resulting backup ? Does it seems to contain the right output ?

**Comment by danielristic** [comment]
Hello @elthariel, since it's an error that's thrown using the default configuration (when using mysql 5.7.31 or newer), it should at least be mentioned in the documentation or part of the example configuration to have `db.additional_options = ["--no-tablespaces"]` (or instruct to grant PROCESS privilege to the mysqldump user).
