### ISSUE TITLE
Not working in Ruby 3.1

### ISSUE THREAD

**Issue by feliperaul** [backup/backup#978]
The backup will fail (locally or on S3) when cycling. Please see pull request #977

**Comment by feliperaul** [comment]
To be more specific, the backups will successfully be stored (either locally or on S3), but they will fail with a `[error] Psych::DisallowedClass: Tried to load unspecified class: Backup::Package` on the cycle phase.

This means the gem will stop removing old backups, and will eventually fill up your disk (if you are using local storage) or grow indefinitely in your S3.

**Comment by schnittchen** [comment]
This is still an issue on `5.0.0.beta.3`. Please reopen.

**Comment by elthariel** [comment]
There are other issues with ruby 3.1. 
They're being fixed in #982
