### ISSUE TITLE
RAILS 7 cannot use backup version 4.x

### ISSUE THREAD

**Issue by helmiatwork** [backup/backup#986]
## What went wrong?

I was trying to add a backup gem to my project but I was wondering why I only get version 3.4, didn't get the newest one

1. bundle add backup
I got gem "backup", "~> 3.4"

**Change the information below to match the details of your computer**

* Operating system: Macbook M1
* Ruby version: 3.1.2
* Tools or services used by backup: Postgresql latest

**Comment by elthariel** [comment]
Hum, I don't think it's related to backup per-say. My first guess is that it's related to the dependency resolution and that some gem in your bundle trigger this ?

In any case, I don't think you should add backup to your rails project Gemfile. This is not a tool that is used by your rails project itself. This is a tool you install on the machine where your project runs. Just do a `gem install` on your machine
